import { useState } from 'react';

const flags = { en: '🇬🇧', de: '🇩🇪', es: '🇪🇸' };
const C = { deep: '#0F0E17', card: '#1E1D2F', text: '#E0DFF0', dim: '#9896B0', crimson: '#E94560', gold: '#F5C842', cyan: '#2CB6D6', violet: '#A855F7', green: '#34D399' };
function L(o: Record<string, string>, l: string) { return o[l] || o.en; }

function PQ({ text, color }: { text: string; color: string }) {
  return (<div style={{ margin: '56px 0', padding: 40, position: 'relative', textAlign: 'center', borderRadius: 16, border: `1px solid ${color}33`, background: `linear-gradient(135deg, ${color}14, ${color}08)` }}>
    <span style={{ position: 'absolute', top: -10, left: 30, fontFamily: "'Playfair Display', serif", fontSize: 80, lineHeight: 1, opacity: 0.15, color }}>&ldquo;</span>
    <p style={{ fontFamily: "'Playfair Display', serif", fontSize: 'clamp(22px, 3vw, 28px)', fontWeight: 700, fontStyle: 'italic', lineHeight: 1.4, color, margin: 0 }}>{text}</p>
  </div>);
}
function ST({ text, color }: { text: string; color: string }) { return <p style={{ fontSize: 22, fontWeight: 700, color: '#fff', margin: '32px 0', paddingLeft: 20, borderLeft: `3px solid ${color}`, lineHeight: 1.5 }}>{text}</p>; }
function Sep() { return (<div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 16, margin: '64px 0' }}><div style={{ width: 40, height: 1, background: `${C.cyan}4D` }} /><div style={{ width: 6, height: 6, borderRadius: '50%', background: C.cyan, opacity: 0.5 }} /><div style={{ width: 40, height: 1, background: `${C.cyan}4D` }} /></div>); }
function SH({ num, title, highlight, color }: { num: string; title: string; highlight: string; color: string }) { return (<div style={{ marginTop: 100, marginBottom: 40 }}><div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 12, letterSpacing: 3, textTransform: 'uppercase', color: C.cyan, marginBottom: 12 }}>{num}</div><h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: 'clamp(28px, 4vw, 40px)', fontWeight: 700, lineHeight: 1.2, color: '#fff', margin: 0 }}>{title}{' '}<span style={{ background: `linear-gradient(135deg, ${color}, ${color}99)`, WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>{highlight}</span></h2><div style={{ width: 50, height: 3, marginTop: 20, borderRadius: 2, background: `linear-gradient(90deg, ${color}, ${color}99)` }} /></div>); }
function Card({ label, text, color }: { label: string; text: string; color: string }) { return (<div style={{ background: C.card, borderRadius: 12, padding: '28px 32px', borderLeft: `3px solid ${color}`, marginBottom: 20 }}><div style={{ fontFamily: "'Playfair Display', serif", fontWeight: 700, fontSize: 20, marginBottom: 8, color }}>{label}</div><p style={{ color: C.dim, fontSize: 17, lineHeight: 1.6, margin: 0 }}>{text}</p></div>); }
function TwoCol({ lt, l, lc, rt, r, rc }: { lt: string; l: string; lc: string; rt: string; r: string; rc: string }) { return (<div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 24, margin: '40px 0' }}>{[[lt,l,lc],[rt,r,rc]].map(([t,x,c],i) => (<div key={i} style={{ padding: 32, borderRadius: 16, background: `linear-gradient(180deg, ${c}1A, ${C.card})`, border: `1px solid ${c}26`, position: 'relative', overflow: 'hidden' }}><div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 3, background: `linear-gradient(90deg, ${c}, ${c}99)` }} /><div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 12, letterSpacing: 3, textTransform: 'uppercase', color: c, marginBottom: 16 }}>{t}</div><p style={{ fontSize: 16, lineHeight: 1.65, color: C.text, margin: 0 }}>{x}</p></div>))}</div>); }
function CTA({ text, sub }: { text: string; sub: string }) { return (<div style={{ margin: '48px 0', padding: 32, background: C.card, borderRadius: 12, textAlign: 'center', border: `1px solid ${C.green}33` }}><p style={{ fontFamily: "'Playfair Display', serif", fontSize: 22, fontWeight: 700, color: C.green, marginBottom: 12 }}>{text}</p><p style={{ fontSize: 16, color: C.dim, margin: 0 }}>{sub}</p></div>); }
function TrioCard({ icon, title, text, color }: { icon: string; title: string; text: string; color: string }) { return (<div style={{ padding: 28, borderRadius: 14, background: C.card, border: '1px solid rgba(255,255,255,0.05)', textAlign: 'center', borderTop: `3px solid ${color}` }}><span style={{ fontSize: 36, display: 'block', marginBottom: 16 }}>{icon}</span><div style={{ fontFamily: "'Playfair Display', serif", fontWeight: 700, fontSize: 18, color, marginBottom: 10 }}>{title}</div><p style={{ fontSize: 15, color: C.dim, lineHeight: 1.55, margin: 0 }}>{text}</p></div>); }

const t = {
  eye: { en: 'Opinion · Data · Evolution · Psychology', de: 'Meinung · Daten · Evolution · Psychologie', es: 'Opinión · Datos · Evolución · Psicología' },
  h1a: { en: 'You Were Already a', de: 'Du warst schon immer eine', es: 'Ya eras una' },
  h1b: { en: 'Data Machine.', de: 'Datenmaschine.', es: 'máquina de datos.' },
  h1c: { en: 'Long Before the', de: 'Lange bevor das', es: 'Mucho antes de que' },
  h1d: { en: 'Internet Existed.', de: 'Internet existierte.', es: 'existiera el internet.' },
  sub: { en: 'The data panic is not about data. It is about a fear we have been trained to feel for centuries.', de: 'Die Datenpanik handelt nicht von Daten. Es geht um eine Angst, zu der wir seit Jahrhunderten konditioniert werden.', es: 'El pánico por los datos no se trata de datos. Se trata de un miedo que nos han entrenado a sentir durante siglos.' },
  scroll: { en: 'Read on', de: 'Weiterlesen', es: 'Sigue leyendo' },
  s1t: { en: 'The Paradox', de: 'Das Paradoxon,', es: 'La paradoja' },
  s1h: { en: 'Nobody Talks About', de: 'über das niemand spricht', es: 'de la que nadie habla' },
  s1p1: { en: 'Data collection is mainstream now. Everyone is talking about it. Governments are regulating it. Headlines are screaming about it. Your uncle at Thanksgiving has opinions about it.', de: 'Datensammlung ist jetzt Mainstream. Jeder redet darüber. Regierungen regulieren es. Schlagzeilen schreien darüber. Dein Onkel beim Familienessen hat Meinungen dazu.', es: 'La recolección de datos es mainstream ahora. Todos hablan de ello. Los gobiernos lo regulan. Los titulares gritan sobre ello. Tu tío en la cena familiar tiene opiniones al respecto.' },
  s1p2: { en: '"They\'re collecting our data." Say it in any room and you will get nodding heads, worried faces, maybe a conspiracy theory or two.', de: '„Die sammeln unsere Daten." Sag das in jedem Raum und du bekommst nickende Köpfe, besorgte Gesichter, vielleicht eine Verschwörungstheorie oder zwei.', es: '«Están recolectando nuestros datos.» Dilo en cualquier sala y obtendrás cabezas asintiendo, caras preocupadas, quizás una teoría conspirativa o dos.' },
  s1p3: { en: 'But here is the part that almost nobody mentions:', de: 'Aber hier ist der Teil, den fast niemand erwähnt:', es: 'Pero aquí está la parte que casi nadie menciona:' },
  s1pq: { en: 'You have been collecting, processing, and transferring data since the moment you were born. Every cell in your body is doing it right now.', de: 'Du sammelst, verarbeitest und überträgst Daten seit dem Moment deiner Geburt. Jede Zelle in deinem Körper tut es gerade jetzt.', es: 'Has estado recolectando, procesando y transfiriendo datos desde el momento en que naciste. Cada célula de tu cuerpo lo está haciendo ahora mismo.' },
  s1p4: { en: 'Your DNA is a data storage system. Your nervous system is a data transfer network. Your immune system collects information about every pathogen it encounters, builds a database, and queries it the next time a threat appears. Your eyes are sensors. Your ears are sensors. Your skin is a sensor array with millions of data points reporting to a central processor that you call your brain.', de: 'Deine DNA ist ein Datenspeichersystem. Dein Nervensystem ist ein Datenübertragungsnetzwerk. Dein Immunsystem sammelt Informationen über jeden Erreger, dem es begegnet, baut eine Datenbank auf und fragt sie ab, wenn das nächste Mal eine Bedrohung auftaucht. Deine Augen sind Sensoren. Deine Ohren sind Sensoren. Deine Haut ist ein Sensor-Array mit Millionen von Datenpunkten, die an einen zentralen Prozessor berichten, den du dein Gehirn nennst.', es: 'Tu ADN es un sistema de almacenamiento de datos. Tu sistema nervioso es una red de transferencia de datos. Tu sistema inmunológico recolecta información sobre cada patógeno que encuentra, construye una base de datos y la consulta la próxima vez que aparece una amenaza. Tus ojos son sensores. Tus oídos son sensores. Tu piel es un array de sensores con millones de puntos de datos que reportan a un procesador central que llamas tu cerebro.' },
  s1p5: { en: 'You are not a person who uses data. You are a data machine that learned to call itself a person.', de: 'Du bist nicht eine Person, die Daten benutzt. Du bist eine Datenmaschine, die gelernt hat, sich eine Person zu nennen.', es: 'No eres una persona que usa datos. Eres una máquina de datos que aprendió a llamarse persona.' },
  s1p6: { en: 'And you have always been one.', de: 'Und das warst du schon immer.', es: 'Y siempre lo has sido.' },
  s2t: { en: 'Data Was Never the', de: 'Daten waren nie das', es: 'Los datos nunca fueron el' },
  s2h: { en: 'Problem', de: 'Problem', es: 'problema' },
  s2p1: { en: 'Let me ask you something uncomfortable. What exactly are you afraid of when you say you are afraid of "data collection"?', de: 'Lass mich dir eine unangenehme Frage stellen. Wovor genau hast du Angst, wenn du sagst, du hast Angst vor „Datensammlung"?', es: 'Permíteme hacerte una pregunta incómoda. ¿De qué exactamente tienes miedo cuando dices que tienes miedo de la «recolección de datos»?' },
  s2p2: { en: 'That someone knows your shopping habits? Your location? Your browsing history? Let\'s be honest: Your neighbors in a medieval village knew more about your private life than any algorithm does today. They knew who you slept with, what you ate, what you earned, what you believed, and what you did at night. There was no privacy. There was no encryption. There was just proximity.', de: 'Dass jemand deine Einkaufsgewohnheiten kennt? Deinen Standort? Deinen Browserverlauf? Seien wir ehrlich: Deine Nachbarn in einem mittelalterlichen Dorf wussten mehr über dein Privatleben als jeder Algorithmus heute. Sie wussten, mit wem du geschlafen hast, was du gegessen hast, was du verdient hast, woran du geglaubt hast und was du nachts getan hast. Es gab keine Privatsphäre. Es gab keine Verschlüsselung. Es gab nur Nähe.', es: '¿Que alguien conozca tus hábitos de compra? ¿Tu ubicación? ¿Tu historial de navegación? Seamos honestos: Tus vecinos en un pueblo medieval sabían más sobre tu vida privada que cualquier algoritmo hoy. Sabían con quién dormías, qué comías, cuánto ganabas, en qué creías y qué hacías por la noche. No había privacidad. No había encriptación. Solo había proximidad.' },
  s2p3: { en: 'Humans have always collected data about each other. We call it gossip. We call it observation. We call it social intelligence. We have been doing it for hundreds of thousands of years, and it is one of the core reasons we survived as a species.', de: 'Menschen haben schon immer Daten übereinander gesammelt. Wir nennen es Klatsch. Wir nennen es Beobachtung. Wir nennen es soziale Intelligenz. Wir tun das seit Hunderttausenden von Jahren, und es ist einer der Kerngründe, warum wir als Spezies überlebt haben.', es: 'Los humanos siempre han recolectado datos sobre los demás. Lo llamamos chisme. Lo llamamos observación. Lo llamamos inteligencia social. Lo hemos hecho durante cientos de miles de años, y es una de las razones fundamentales por las que sobrevivimos como especie.' },
  s2st: { en: 'The exchange of information is not a modern invention. It is a biological imperative.', de: 'Der Austausch von Informationen ist keine moderne Erfindung. Er ist ein biologischer Imperativ.', es: 'El intercambio de información no es un invento moderno. Es un imperativo biológico.' },
  s2p4: { en: 'So if data transfer is not new, why does it suddenly feel so threatening? Why do billions of people who walk around as biological data machines, transmitting and receiving information every waking second, feel personally violated when a digital system does the same thing?', de: 'Wenn also Datenübertragung nichts Neues ist, warum fühlt es sich plötzlich so bedrohlich an? Warum fühlen sich Milliarden von Menschen, die als biologische Datenmaschinen herumlaufen und jede wache Sekunde Informationen senden und empfangen, persönlich verletzt, wenn ein digitales System dasselbe tut?', es: 'Entonces, si la transferencia de datos no es nueva, ¿por qué de repente se siente tan amenazante? ¿Por qué miles de millones de personas que caminan como máquinas biológicas de datos, transmitiendo y recibiendo información cada segundo despierto, se sienten personalmente violadas cuando un sistema digital hace lo mismo?' },
  s2p5: { en: 'The answer is not in the data. The answer is in the story we have been told about the data.', de: 'Die Antwort liegt nicht in den Daten. Die Antwort liegt in der Geschichte, die man uns über die Daten erzählt hat.', es: 'La respuesta no está en los datos. La respuesta está en la historia que nos han contado sobre los datos.' },
  s3t: { en: 'The Negativity Machine', de: 'Die Negativitätsmaschine,', es: 'La máquina de negatividad' },
  s3h: { en: 'You Never Signed Up For', de: 'für die du dich nie angemeldet hast', es: 'a la que nunca te suscribiste' },
  s3p1: { en: 'Here is what a decade of studying human psychology has made painfully clear to me: We are wired to see threats. Not opportunities. Not potential. Threats.', de: 'Hier ist, was ein Jahrzehnt des Studiums menschlicher Psychologie mir schmerzlich klargemacht hat: Wir sind darauf programmiert, Bedrohungen zu sehen. Nicht Chancen. Nicht Potenzial. Bedrohungen.', es: 'Esto es lo que una década estudiando psicología humana me ha dejado dolorosamente claro: Estamos programados para ver amenazas. No oportunidades. No potencial. Amenazas.' },
  s3p2: { en: 'This is the negativity bias, and it is one of the most well-documented phenomena in behavioral science. Negative information is processed faster, remembered longer, and weighted more heavily in decision-making than positive information. This is not a flaw. It kept our ancestors alive. The ones who assumed the rustling in the bushes was a predator survived. The ones who assumed it was just the wind did not.', de: 'Das ist der Negativitätsbias, und er ist eines der am besten dokumentierten Phänomene der Verhaltenswissenschaft. Negative Informationen werden schneller verarbeitet, länger erinnert und bei Entscheidungen schwerer gewichtet als positive. Das ist kein Fehler. Es hielt unsere Vorfahren am Leben. Die, die annahmen, das Rascheln im Gebüsch sei ein Raubtier, überlebten. Die, die annahmen, es sei nur der Wind, nicht.', es: 'Esto es el sesgo de negatividad, y es uno de los fenómenos mejor documentados en la ciencia del comportamiento. La información negativa se procesa más rápido, se recuerda más tiempo y se pondera más en la toma de decisiones que la información positiva. Esto no es un defecto. Mantuvo vivos a nuestros ancestros. Los que asumían que el crujido en los arbustos era un depredador sobrevivieron. Los que asumían que solo era el viento, no.' },
  s3p3: { en: 'But here is the problem: That same survival mechanism is now being weaponized.', de: 'Aber hier ist das Problem: Genau dieser Überlebensmechanismus wird jetzt als Waffe eingesetzt.', es: 'Pero aquí está el problema: Ese mismo mecanismo de supervivencia está siendo convertido en arma.' },
  s3cards: {
    en: [
      { l: 'The Media Equation', t: 'Every headline about data breaches, surveillance, and privacy violations is designed to trigger your threat response. Not because the information is false, but because fear generates clicks. Attention is currency. And your negativity bias is the printing press.' },
      { l: 'The Conditioning Loop', t: 'We have been conditioned for decades, possibly centuries, to direct our attention toward danger. The news cycle feeds on it. The political machine runs on it. The marketing industry, ironically, sells solutions to the very fears it helped create: Gratitude journals, mindfulness apps, happiness calendars. The positivity industry is a reaction to the negativity machine.' },
      { l: 'The Displacement Effect', t: 'When people say "bad things will be done with our data," they are not wrong. Bad things will be done. But bad things have always been done, with or without digital data. Manipulation, exploitation, control: These are human behaviors, not technological ones. Blaming the data is like blaming the road for the car crash.' },
    ],
    de: [
      { l: 'Die Mediengleichung', t: 'Jede Schlagzeile über Datenlecks, Überwachung und Datenschutzverletzungen ist darauf ausgelegt, deine Bedrohungsreaktion auszulösen. Nicht weil die Information falsch ist, sondern weil Angst Klicks generiert. Aufmerksamkeit ist Währung. Und dein Negativitätsbias ist die Druckerpresse.' },
      { l: 'Die Konditionierungsschleife', t: 'Wir werden seit Jahrzehnten, möglicherweise Jahrhunderten, darauf konditioniert, unsere Aufmerksamkeit auf Gefahr zu richten. Der Nachrichtenzyklus nährt sich davon. Die politische Maschinerie läuft damit. Die Marketingindustrie verkauft, ironischerweise, Lösungen für genau die Ängste, die sie mitgeschaffen hat: Dankbarkeitstagebücher, Achtsamkeits-Apps, Glückskalender. Die Positivitätsindustrie ist eine Reaktion auf die Negativitätsmaschine.' },
      { l: 'Der Verdrängungseffekt', t: 'Wenn Menschen sagen „mit unseren Daten werden schlechte Dinge gemacht", liegen sie nicht falsch. Schlechte Dinge werden gemacht. Aber schlechte Dinge wurden immer gemacht, mit oder ohne digitale Daten. Manipulation, Ausbeutung, Kontrolle: Das sind menschliche Verhaltensweisen, keine technologischen. Die Daten zu beschuldigen ist wie die Straße für den Autounfall verantwortlich zu machen.' },
    ],
    es: [
      { l: 'La ecuación mediática', t: 'Cada titular sobre brechas de datos, vigilancia y violaciones de privacidad está diseñado para activar tu respuesta de amenaza. No porque la información sea falsa, sino porque el miedo genera clics. La atención es moneda. Y tu sesgo de negatividad es la imprenta.' },
      { l: 'El bucle de condicionamiento', t: 'Hemos sido condicionados durante décadas, posiblemente siglos, a dirigir nuestra atención hacia el peligro. El ciclo de noticias se alimenta de ello. La maquinaria política funciona con ello. La industria del marketing, irónicamente, vende soluciones a los mismos miedos que ayudó a crear: Diarios de gratitud, apps de mindfulness, calendarios de felicidad. La industria de la positividad es una reacción a la máquina de negatividad.' },
      { l: 'El efecto de desplazamiento', t: 'Cuando la gente dice «se harán cosas malas con nuestros datos», no están equivocados. Se harán cosas malas. Pero siempre se han hecho cosas malas, con o sin datos digitales. Manipulación, explotación, control: Estos son comportamientos humanos, no tecnológicos. Culpar a los datos es como culpar a la carretera por el choque de autos.' },
    ],
  },
  s3pq: { en: 'The fear of data is not really about data. It is about a deeply conditioned reflex to assume the worst, amplified by industries that profit from your anxiety.', de: 'Die Angst vor Daten handelt nicht wirklich von Daten. Es geht um einen tief konditionierten Reflex, das Schlimmste anzunehmen, verstärkt durch Industrien, die von deiner Angst profitieren.', es: 'El miedo a los datos no se trata realmente de datos. Se trata de un reflejo profundamente condicionado de asumir lo peor, amplificado por industrias que lucran con tu ansiedad.' },
  s4t: { en: 'The Biology', de: 'Die Biologie,', es: 'La biología' },
  s4h: { en: 'They Conveniently Ignore', de: 'die sie bequem ignorieren', es: 'que convenientemente ignoran' },
  s4p1: { en: 'Here is what gets lost in every data debate, every privacy panic, every AI fear cycle: The things people are afraid of are not caused by data transfer. They are caused by biology and psychology. And those forces exist independently of any technology.', de: 'Hier ist, was in jeder Datendebatte, jeder Privatsphärenpanik, jedem KI-Angstzyklus verloren geht: Die Dinge, vor denen Menschen Angst haben, werden nicht durch Datenübertragung verursacht. Sie werden durch Biologie und Psychologie verursacht. Und diese Kräfte existieren unabhängig von jeder Technologie.', es: 'Esto es lo que se pierde en cada debate sobre datos, cada pánico de privacidad, cada ciclo de miedo a la IA: Las cosas que la gente teme no son causadas por la transferencia de datos. Son causadas por la biología y la psicología. Y esas fuerzas existen independientemente de cualquier tecnología.' },
  s4p2: { en: 'Manipulation existed before the internet. Propaganda existed before social media. Surveillance existed before cameras. Exploitation existed before databases. These are not data problems. These are human problems, rooted in evolutionary drives for power, control, and dominance that have been with us since the first primate figured out that information is leverage.', de: 'Manipulation existierte vor dem Internet. Propaganda existierte vor Social Media. Überwachung existierte vor Kameras. Ausbeutung existierte vor Datenbanken. Das sind keine Datenprobleme. Das sind menschliche Probleme, verwurzelt in evolutionären Trieben nach Macht, Kontrolle und Dominanz, die uns begleiten, seit der erste Primat herausfand, dass Information Hebelwirkung ist.', es: 'La manipulación existía antes del internet. La propaganda existía antes de las redes sociales. La vigilancia existía antes de las cámaras. La explotación existía antes de las bases de datos. Estos no son problemas de datos. Son problemas humanos, enraizados en impulsos evolutivos de poder, control y dominancia que nos acompañan desde que el primer primate descubrió que la información es palanca.' },
  s4lt: { en: 'What People Fear', de: 'Wovor Menschen Angst haben', es: 'Lo que la gente teme' },
  s4l: { en: '"Our data will be used for bad things." And yes, sometimes it is. But the bad things, manipulation, deception, coercion, exploitation, would happen regardless. The tools change. The behaviors do not. A con artist in 1820 used a handshake and a convincing story. A con artist in 2025 uses an email and a convincing link. The mechanism is different. The psychology is identical.', de: '„Unsere Daten werden für schlechte Dinge benutzt." Und ja, manchmal stimmt das. Aber die schlechten Dinge, Manipulation, Täuschung, Nötigung, Ausbeutung, würden trotzdem passieren. Die Werkzeuge ändern sich. Das Verhalten nicht. Ein Betrüger im Jahr 1820 benutzte einen Handschlag und eine überzeugende Geschichte. Ein Betrüger im Jahr 2025 benutzt eine E-Mail und einen überzeugenden Link. Der Mechanismus ist anders. Die Psychologie ist identisch.', es: '«Nuestros datos serán usados para cosas malas.» Y sí, a veces lo son. Pero las cosas malas, la manipulación, el engaño, la coerción, la explotación, sucederían de todas formas. Las herramientas cambian. Los comportamientos no. Un estafador en 1820 usaba un apretón de manos y una historia convincente. Un estafador en 2025 usa un email y un enlace convincente. El mecanismo es diferente. La psicología es idéntica.' },
  s4rt: { en: 'What People Miss', de: 'Was Menschen übersehen', es: 'Lo que la gente no ve' },
  s4r: { en: 'The same data infrastructure that enables surveillance also enables breakthroughs in medicine, education, communication, accessibility, and human connection. The same AI that "collects your data" can also diagnose diseases years earlier, translate languages in real time, and give every person on Earth access to knowledge that used to be locked behind institutional walls.', de: 'Dieselbe Dateninfrastruktur, die Überwachung ermöglicht, ermöglicht auch Durchbrüche in Medizin, Bildung, Kommunikation, Barrierefreiheit und menschlicher Verbindung. Dieselbe KI, die „deine Daten sammelt", kann auch Krankheiten Jahre früher diagnostizieren, Sprachen in Echtzeit übersetzen und jedem Menschen auf der Erde Zugang zu Wissen geben, das früher hinter institutionellen Mauern verschlossen war.', es: 'La misma infraestructura de datos que permite la vigilancia también permite avances en medicina, educación, comunicación, accesibilidad y conexión humana. La misma IA que «recolecta tus datos» también puede diagnosticar enfermedades años antes, traducir idiomas en tiempo real y dar a cada persona en la Tierra acceso a conocimiento que antes estaba encerrado detrás de muros institucionales.' },
  s4st: { en: 'The question was never whether data can be misused. Of course it can. The question is whether we are going to let a conditioned fear response prevent us from seeing what it also makes possible.', de: 'Die Frage war nie, ob Daten missbraucht werden können. Natürlich können sie das. Die Frage ist, ob wir eine konditionierte Angstreaktion uns davon abhalten lassen, zu sehen, was sie auch möglich machen.', es: 'La pregunta nunca fue si los datos pueden ser mal utilizados. Por supuesto que sí. La pregunta es si vamos a dejar que una respuesta de miedo condicionada nos impida ver lo que también hacen posible.' },
  s5t: { en: 'The Fear of Being', de: 'Die Angst, ersetzt', es: 'El miedo a ser' },
  s5h: { en: 'Replaced', de: 'zu werden', es: 'reemplazado' },
  s5p1: { en: 'Now let\'s talk about the deeper fear. The one underneath the data panic, underneath the privacy concerns, underneath all the headlines. The one people feel in their gut but rarely say out loud:', de: 'Reden wir jetzt über die tiefere Angst. Die unter der Datenpanik, unter den Datenschutzbedenken, unter all den Schlagzeilen. Die, die Menschen im Bauch spüren, aber selten laut aussprechen:', es: 'Ahora hablemos del miedo más profundo. El que está debajo del pánico por los datos, debajo de las preocupaciones de privacidad, debajo de todos los titulares. El que la gente siente en las entrañas pero rara vez dice en voz alta:' },
  s5pq: { en: 'What if I become irrelevant?', de: 'Was, wenn ich irrelevant werde?', es: '¿Y si me vuelvo irrelevante?' },
  s5p2: { en: 'This fear is real. And it is completely, biologically normal. Every species that has ever existed has faced the pressure of being outcompeted, outadapted, outevolved. It is the fundamental engine of natural selection. And it triggers one of the deepest anxiety responses we have.', de: 'Diese Angst ist real. Und sie ist vollkommen, biologisch normal. Jede Spezies, die jemals existiert hat, stand unter dem Druck, übertroffen, überangepasst, überevolviert zu werden. Es ist der fundamentale Motor der natürlichen Selektion. Und er löst eine der tiefsten Angstreaktionen aus, die wir haben.', es: 'Este miedo es real. Y es completamente, biológicamente normal. Cada especie que ha existido ha enfrentado la presión de ser superada, superadaptada, superevolucionada. Es el motor fundamental de la selección natural. Y desencadena una de las respuestas de ansiedad más profundas que tenemos.' },
  s5p3: { en: 'But here is what the fear blinds us to: Adaptation is not the same as replacement.', de: 'Aber hier ist, wofür die Angst uns blind macht: Anpassung ist nicht dasselbe wie Ersetzung.', es: 'Pero esto es lo que el miedo nos impide ver: Adaptación no es lo mismo que reemplazo.' },
  s5p4: { en: 'Look at the history of life on this planet. A staggering majority of all species that have ever lived are now extinct. But the ones that survived did not survive by resisting change. They survived by integrating new information. By processing signals from their environment and adjusting. By treating new data not as a threat, but as raw material for evolution.', de: 'Schau dir die Geschichte des Lebens auf diesem Planeten an. Eine überwältigende Mehrheit aller Spezies, die jemals gelebt haben, sind jetzt ausgestorben. Aber die, die überlebt haben, überlebten nicht, indem sie sich gegen Veränderung wehrten. Sie überlebten, indem sie neue Informationen integrierten. Indem sie Signale aus ihrer Umgebung verarbeiteten und sich anpassten. Indem sie neue Daten nicht als Bedrohung behandelten, sondern als Rohmaterial für Evolution.', es: 'Mira la historia de la vida en este planeta. Una mayoría abrumadora de todas las especies que han existido están ahora extintas. Pero las que sobrevivieron no lo hicieron resistiéndose al cambio. Sobrevivieron integrando nueva información. Procesando señales de su entorno y ajustándose. Tratando los nuevos datos no como una amenaza, sino como materia prima para la evolución.' },
  s5st: { en: 'The species that judged new information instead of processing it? They are fossils now.', de: 'Die Spezies, die neue Informationen verurteilten, statt sie zu verarbeiten? Sie sind jetzt Fossilien.', es: 'Las especies que juzgaron la nueva información en vez de procesarla? Son fósiles ahora.' },
  s5p5: { en: 'This is not a metaphor. This is the literal mechanism of survival. And it applies to us right now, in this moment, with this technology.', de: 'Das ist keine Metapher. Das ist der buchstäbliche Mechanismus des Überlebens. Und er gilt für uns genau jetzt, in diesem Moment, mit dieser Technologie.', es: 'Esto no es una metáfora. Es el mecanismo literal de supervivencia. Y se aplica a nosotros ahora mismo, en este momento, con esta tecnología.' },
  s6t: { en: 'The Extended Human:', de: 'Der erweiterte Mensch:', es: 'El humano extendido:' },
  s6h: { en: 'What AI Actually Offers', de: 'Was KI tatsächlich bietet', es: 'Lo que la IA realmente ofrece' },
  s6p1: { en: 'So here is the reframe. The one that changes everything if you let it:', de: 'Hier also der Perspektivwechsel. Der, der alles verändert, wenn du ihn zulässt:', es: 'Aquí está el reencuadre. El que lo cambia todo si lo permites:' },
  s6p2: { en: 'AI is not a replacement for humans. It is an extension of humans.', de: 'KI ist kein Ersatz für Menschen. Sie ist eine Erweiterung von Menschen.', es: 'La IA no es un reemplazo para los humanos. Es una extensión de los humanos.' },
  s6p3: { en: 'We have always extended ourselves. Language extended our ability to share thoughts. Writing extended our memory. The printing press extended our reach. The telescope extended our vision. The internet extended our connectivity. Every major leap in human capability came from a tool that let us do more with the same biology.', de: 'Wir haben uns schon immer erweitert. Sprache erweiterte unsere Fähigkeit, Gedanken zu teilen. Schrift erweiterte unser Gedächtnis. Der Buchdruck erweiterte unsere Reichweite. Das Teleskop erweiterte unser Sehen. Das Internet erweiterte unsere Vernetzung. Jeder große Sprung in menschlicher Leistungsfähigkeit kam von einem Werkzeug, das uns erlaubte, mit derselben Biologie mehr zu tun.', es: 'Siempre nos hemos extendido. El lenguaje extendió nuestra capacidad de compartir pensamientos. La escritura extendió nuestra memoria. La imprenta extendió nuestro alcance. El telescopio extendió nuestra visión. El internet extendió nuestra conectividad. Cada gran salto en la capacidad humana vino de una herramienta que nos permitió hacer más con la misma biología.' },
  s6p4: { en: 'AI is the next extension. And it might be the most powerful one yet.', de: 'KI ist die nächste Erweiterung. Und sie könnte die mächtigste sein, die es je gab.', es: 'La IA es la siguiente extensión. Y podría ser la más poderosa hasta ahora.' },
  trio: {
    en: [{ i: '🧠', t: 'Extended Cognition', d: 'Access to knowledge that would take a lifetime to acquire. Pattern recognition across datasets no human brain could process alone. The ability to think at scale.' }, { i: '🌍', t: 'Extended Perception', d: 'Systems that can see what we miss. Analyze behavioral patterns, health signals, environmental data, market movements. Our senses, amplified beyond biological limits.' }, { i: '⚡', t: 'Extended Agency', d: 'The power to act on more information, faster, with greater precision. Not replacing human decisions, but giving humans better inputs to decide with.' }],
    de: [{ i: '🧠', t: 'Erweiterte Kognition', d: 'Zugang zu Wissen, für das man ein Leben lang bräuchte. Mustererkennung über Datensätze hinweg, die kein menschliches Gehirn allein verarbeiten könnte. Die Fähigkeit, im großen Maßstab zu denken.' }, { i: '🌍', t: 'Erweiterte Wahrnehmung', d: 'Systeme, die sehen können, was wir übersehen. Verhaltensmuster, Gesundheitssignale, Umweltdaten, Marktbewegungen analysieren. Unsere Sinne, über biologische Grenzen hinaus verstärkt.' }, { i: '⚡', t: 'Erweiterte Handlungsfähigkeit', d: 'Die Kraft, auf mehr Informationen schneller und präziser zu handeln. Nicht menschliche Entscheidungen ersetzen, sondern Menschen bessere Grundlagen zum Entscheiden geben.' }],
    es: [{ i: '🧠', t: 'Cognición extendida', d: 'Acceso a conocimiento que tomaría toda una vida adquirir. Reconocimiento de patrones a través de conjuntos de datos que ningún cerebro humano podría procesar solo. La capacidad de pensar a escala.' }, { i: '🌍', t: 'Percepción extendida', d: 'Sistemas que pueden ver lo que nosotros no. Analizar patrones de comportamiento, señales de salud, datos ambientales, movimientos del mercado. Nuestros sentidos, amplificados más allá de los límites biológicos.' }, { i: '⚡', t: 'Agencia extendida', d: 'El poder de actuar con más información, más rápido, con mayor precisión. No reemplazar decisiones humanas, sino dar a los humanos mejores insumos para decidir.' }],
  },
  s6p5: { en: 'This is what we are actually being offered. Not surveillance. Not control. Not replacement. But the ability to become more of what we already are. Processors of information. Recognizers of patterns. Builders of meaning from noise.', de: 'Das ist, was uns tatsächlich angeboten wird. Nicht Überwachung. Nicht Kontrolle. Nicht Ersetzung. Sondern die Fähigkeit, mehr von dem zu werden, was wir bereits sind. Verarbeiter von Informationen. Erkenner von Mustern. Erbauer von Bedeutung aus Rauschen.', es: 'Esto es lo que realmente se nos ofrece. No vigilancia. No control. No reemplazo. Sino la capacidad de convertirnos en más de lo que ya somos. Procesadores de información. Reconocedores de patrones. Constructores de significado a partir del ruido.' },
  s6pq: { en: 'We are not being replaced. We are being upgraded. But only if we choose to see it that way.', de: 'Wir werden nicht ersetzt. Wir werden erweitert. Aber nur, wenn wir es so sehen wollen.', es: 'No estamos siendo reemplazados. Estamos siendo expandidos. Pero solo si elegimos verlo así.' },
  s7t: { en: 'The Choice', de: 'Die Entscheidung,', es: 'La decisión' },
  s7h: { en: 'That Has Always Been Yours', de: 'die immer deine war', es: 'que siempre fue tuya' },
  s7p1: { en: 'Here is the core of it all. The part that nobody in the data debate wants to admit:', de: 'Hier ist der Kern von allem. Der Teil, den niemand in der Datendebatte zugeben will:', es: 'Aquí está el centro de todo. La parte que nadie en el debate sobre datos quiere admitir:' },
  s7p2: { en: 'It has always been your choice.', de: 'Es war immer deine Entscheidung.', es: 'Siempre fue tu decisión.' },
  s7p3: { en: 'Not the choice of whether data exists. It does. It always has. Your cells are exchanging it right now. Your brain is processing it right now. The universe runs on it.', de: 'Nicht die Entscheidung, ob Daten existieren. Das tun sie. Das haben sie immer. Deine Zellen tauschen sie gerade aus. Dein Gehirn verarbeitet sie gerade. Das Universum läuft damit.', es: 'No la decisión de si los datos existen. Existen. Siempre lo han hecho. Tus células los están intercambiando ahora mismo. Tu cerebro los está procesando ahora mismo. El universo funciona con ellos.' },
  s7p4: { en: 'The choice is what you do with it. The choice is whether you let a conditioned fear response, amplified by media cycles and negativity bias and centuries of threat-focused conditioning, dictate how you relate to the most powerful set of tools humanity has ever built.', de: 'Die Entscheidung ist, was du damit machst. Die Entscheidung ist, ob du eine konditionierte Angstreaktion, verstärkt durch Medienzyklen und Negativitätsbias und Jahrhunderte bedrohungsfokussierter Konditionierung, bestimmen lässt, wie du dich zu den mächtigsten Werkzeugen verhältst, die die Menschheit je gebaut hat.', es: 'La decisión es qué haces con ellos. La decisión es si dejas que una respuesta de miedo condicionada, amplificada por ciclos mediáticos, sesgo de negatividad y siglos de condicionamiento enfocado en amenazas, dicte cómo te relacionas con el conjunto de herramientas más poderoso que la humanidad ha construido.' },
  s7p5: { en: 'Or whether you do what every successful organism in the history of life has done: Process the new information. Adapt. Extend. Evolve.', de: 'Oder ob du das tust, was jeder erfolgreiche Organismus in der Geschichte des Lebens getan hat: Die neuen Informationen verarbeiten. Anpassen. Erweitern. Evolvieren.', es: 'O si haces lo que cada organismo exitoso en la historia de la vida ha hecho: Procesar la nueva información. Adaptarte. Extenderte. Evolucionar.' },
  cta: { en: 'The data was never the danger. Your relationship to it is.', de: 'Die Daten waren nie die Gefahr. Deine Beziehung zu ihnen schon.', es: 'Los datos nunca fueron el peligro. Tu relación con ellos sí.' },
  ctaSub: { en: 'And that relationship is something you can change right now.', de: 'Und diese Beziehung ist etwas, das du genau jetzt ändern kannst.', es: 'Y esa relación es algo que puedes cambiar ahora mismo.' },
  s7p6: { en: 'Natural catastrophes have always come. Species have always faced extinction. The ones that treated new signals as threats to resist, instead of information to integrate, are the ones that disappeared.', de: 'Naturkatastrophen gab es immer. Spezies standen immer vor dem Aussterben. Die, die neue Signale als Bedrohungen behandelten, denen man widerstehen muss, statt als Informationen, die man integrieren sollte, sind die, die verschwunden sind.', es: 'Las catástrofes naturales siempre han llegado. Las especies siempre han enfrentado la extinción. Las que trataron las nuevas señales como amenazas a resistir, en vez de información a integrar, son las que desaparecieron.' },
  s7p7: { en: 'We are at one of those moments now. AI, data, extended cognition: These are not threats to humanity. They are invitations to become a version of humanity we have not seen yet.', de: 'Wir sind jetzt an einem dieser Momente. KI, Daten, erweiterte Kognition: Das sind keine Bedrohungen für die Menschheit. Sie sind Einladungen, eine Version der Menschheit zu werden, die wir noch nicht gesehen haben.', es: 'Estamos en uno de esos momentos ahora. IA, datos, cognición extendida: Estas no son amenazas para la humanidad. Son invitaciones a convertirnos en una versión de la humanidad que aún no hemos visto.' },
  s7p8: { en: 'The only question is whether you will accept the invitation, or let a million years of threat conditioning decide for you.', de: 'Die einzige Frage ist, ob du die Einladung annimmst, oder ob du eine Million Jahre Bedrohungskonditionierung für dich entscheiden lässt.', es: 'La única pregunta es si aceptarás la invitación, o dejarás que un millón de años de condicionamiento de amenazas decida por ti.' },
  finA: { en: 'You were always a data machine. The only thing that changed is you finally have the tools to', de: 'Du warst schon immer eine Datenmaschine. Das Einzige, was sich geändert hat, ist, dass du endlich die Werkzeuge hast, um', es: 'Siempre fuiste una máquina de datos. Lo único que cambió es que finalmente tienes las herramientas para' },
  finB: { en: 'become a great one.', de: 'eine großartige zu werden.', es: 'convertirte en una extraordinaria.' },
  bio: {
    en: 'CEO & System Architect of ONIOKO. I build extended human systems and Observational Perception Models that let people see what the human eye cannot. Over a decade in psychology and human cognition taught me one thing: I do not build tools that replace people. I build tools that extend them.',
    de: 'CEO & System Architect von ONIOKO. Ich baue Extended Human Systems und Observational Perception Models, die Menschen sehen lassen, was das menschliche Auge nicht kann. Über ein Jahrzehnt in Psychologie und menschlicher Kognition haben mich eines gelehrt: Ich baue keine Werkzeuge, die Menschen ersetzen. Ich baue Werkzeuge, die sie erweitern.',
    es: 'CEO & System Architect de ONIOKO. Construyo sistemas de extensión humana y Modelos de Percepción Observacional que permiten a las personas ver lo que el ojo humano no puede. Más de una década en psicología y cognición humana me enseñaron algo: No construyo herramientas que reemplacen a las personas. Construyo herramientas que las expanden.',
  },
};

const cardColors = [C.cyan, C.green, C.gold];
const trioColors = [C.cyan, C.gold, C.green];
const p = { marginBottom: 24 };

export default function DataMachine() {
  const [lang, setLang] = useState<'en'|'de'|'es'>('en');
  return (
    <div style={{ minHeight: '100vh', background: C.deep, fontFamily: "'Source Sans 3', sans-serif", fontSize: 19, lineHeight: 1.75, color: C.text }}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;0,900;1,400;1,700&family=Source+Sans+3:ital,wght@0,300;0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;600&display=swap');
        @keyframes heroPulse{0%,100%{opacity:.5;transform:translateX(-50%) scale(1)}50%{opacity:.85;transform:translateX(-50%) scale(1.15)}}
        @keyframes bounceDown{0%,100%{transform:rotate(45deg) translateY(0)}50%{transform:rotate(45deg) translateY(6px)}}
        @keyframes finalePulse{0%,100%{opacity:.3}50%{opacity:.6}}`}</style>

      <div style={{ position: 'fixed', top: 20, right: 20, zIndex: 1000, display: 'flex', gap: 8, padding: '8px 12px', background: 'rgba(30,29,47,0.9)', backdropFilter: 'blur(12px)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 12 }}>
        {(['en','de','es']).map(l => <button key={l} onClick={() => setLang(l)} style={{ width: 36, height: 26, borderRadius: 6, fontSize: 18, display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', border: lang === l ? `2px solid ${C.cyan}` : '2px solid transparent', background: lang === l ? `${C.cyan}1A` : 'rgba(255,255,255,0.05)' }}>{flags[l]}</button>)}
      </div>

      <section style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', textAlign: 'center', padding: '60px 24px', position: 'relative', overflow: 'hidden' }}>
        <div style={{ position: 'absolute', top: -200, left: '50%', transform: 'translateX(-50%)', width: 900, height: 900, background: `radial-gradient(circle, ${C.cyan}1F 0%, ${C.violet}0F 40%, transparent 70%)`, pointerEvents: 'none', animation: 'heroPulse 6s ease-in-out infinite' }} />
        <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 13, letterSpacing: 4, textTransform: 'uppercase', color: C.cyan, marginBottom: 32 }}>{L(t.eye, lang)}</div>
        <h1 style={{ fontFamily: "'Playfair Display', serif", fontSize: 'clamp(36px, 6vw, 72px)', fontWeight: 900, lineHeight: 1.05, color: '#fff', maxWidth: 850, margin: 0 }}>
          {L(t.h1a, lang)}{' '}<span style={{ background: `linear-gradient(135deg, ${C.cyan}, ${C.green})`, WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>{L(t.h1b, lang)}</span>{' '}{L(t.h1c, lang)}{' '}<span style={{ background: `linear-gradient(135deg, ${C.crimson}, ${C.gold})`, WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>{L(t.h1d, lang)}</span>
        </h1>
        <p style={{ fontFamily: "'Playfair Display', serif", fontSize: 'clamp(18px, 2.5vw, 26px)', fontStyle: 'italic', color: C.dim, maxWidth: 640, marginTop: 28 }}>{L(t.sub, lang)}</p>
        <div style={{ marginTop: 48, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8 }}>
          <div style={{ width: 60, height: 2, background: `linear-gradient(90deg, ${C.cyan}, ${C.green})`, marginBottom: 16 }} />
          <div style={{ fontWeight: 700, fontSize: 16, color: '#fff', letterSpacing: 1 }}>JUAN SCHUBERT</div>
          <div style={{ fontSize: 14, color: C.dim }}>ONIOKO · 10+ Years in Psychology & Human Cognition</div>
        </div>
        <div style={{ position: 'absolute', bottom: 40, left: '50%', transform: 'translateX(-50%)', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8 }}>
          <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 11, letterSpacing: 3, textTransform: 'uppercase', color: C.dim }}>{L(t.scroll, lang)}</span>
          <div style={{ width: 20, height: 20, borderRight: `2px solid ${C.cyan}`, borderBottom: `2px solid ${C.cyan}`, transform: 'rotate(45deg)', animation: 'bounceDown 2s ease-in-out infinite' }} />
        </div>
      </section>

      <article style={{ maxWidth: 760, margin: '0 auto', padding: '0 24px 120px' }}>
        <SH num="01" title={L(t.s1t, lang)} highlight={L(t.s1h, lang)} color={C.cyan} />
        <p style={p}>{L(t.s1p1, lang)}</p>
        <p style={p}><strong style={{ color: '#fff' }}>{L(t.s1p2, lang)}</strong></p>
        <p style={p}>{L(t.s1p3, lang)}</p>
        <PQ text={L(t.s1pq, lang)} color={C.cyan} />
        <p style={p}>{L(t.s1p4, lang)}</p>
        <p style={p}><em>{L(t.s1p5, lang)}</em></p>
        <p style={p}>{L(t.s1p6, lang)}</p>
        <Sep />

        <SH num="02" title={L(t.s2t, lang)} highlight={L(t.s2h, lang)} color={C.crimson} />
        <p style={p}>{L(t.s2p1, lang)}</p>
        <p style={p}>{L(t.s2p2, lang)}</p>
        <p style={p}>{L(t.s2p3, lang)}</p>
        <ST text={L(t.s2st, lang)} color={C.cyan} />
        <p style={p}>{L(t.s2p4, lang)}</p>
        <p style={p}>{L(t.s2p5, lang)}</p>
        <Sep />

        <SH num="03" title={L(t.s3t, lang)} highlight={L(t.s3h, lang)} color={C.gold} />
        <p style={p}>{L(t.s3p1, lang)}</p>
        <p style={p}>{L(t.s3p2, lang)}</p>
        <p style={p}>{L(t.s3p3, lang)}</p>
        {t.s3cards[lang].map((c, i) => <Card key={i} label={c.l} text={c.t} color={cardColors[i]} />)}
        <PQ text={L(t.s3pq, lang)} color={C.gold} />
        <Sep />

        <SH num="04" title={L(t.s4t, lang)} highlight={L(t.s4h, lang)} color={C.green} />
        <p style={p}>{L(t.s4p1, lang)}</p>
        <p style={p}>{L(t.s4p2, lang)}</p>
        <TwoCol lt={L(t.s4lt, lang)} l={L(t.s4l, lang)} lc={C.crimson} rt={L(t.s4rt, lang)} r={L(t.s4r, lang)} rc={C.green} />
        <ST text={L(t.s4st, lang)} color={C.green} />
        <Sep />

        <SH num="05" title={L(t.s5t, lang)} highlight={L(t.s5h, lang)} color={C.crimson} />
        <p style={p}>{L(t.s5p1, lang)}</p>
        <PQ text={L(t.s5pq, lang)} color={C.crimson} />
        <p style={p}>{L(t.s5p2, lang)}</p>
        <p style={p}>{L(t.s5p3, lang)}</p>
        <p style={p}>{L(t.s5p4, lang)}</p>
        <ST text={L(t.s5st, lang)} color={C.crimson} />
        <p style={p}>{L(t.s5p5, lang)}</p>
        <Sep />

        <SH num="06" title={L(t.s6t, lang)} highlight={L(t.s6h, lang)} color={C.violet} />
        <p style={p}>{L(t.s6p1, lang)}</p>
        <p style={p}><em>{L(t.s6p2, lang)}</em></p>
        <p style={p}>{L(t.s6p3, lang)}</p>
        <p style={p}>{L(t.s6p4, lang)}</p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 20, margin: '40px 0' }}>
          {t.trio[lang].map((tr, i) => <TrioCard key={i} icon={tr.i} title={tr.t} text={tr.d} color={trioColors[i]} />)}
        </div>
        <p style={p}>{L(t.s6p5, lang)}</p>
        <PQ text={L(t.s6pq, lang)} color={C.violet} />
        <Sep />

        <SH num="07" title={L(t.s7t, lang)} highlight={L(t.s7h, lang)} color={C.gold} />
        <p style={p}>{L(t.s7p1, lang)}</p>
        <p style={p}><strong style={{ color: '#fff' }}>{L(t.s7p2, lang)}</strong></p>
        <p style={p}>{L(t.s7p3, lang)}</p>
        <p style={p}>{L(t.s7p4, lang)}</p>
        <p style={p}>{L(t.s7p5, lang)}</p>
        <CTA text={L(t.cta, lang)} sub={L(t.ctaSub, lang)} />
        <p style={p}>{L(t.s7p6, lang)}</p>
        <p style={p}>{L(t.s7p7, lang)}</p>
        <p style={p}>{L(t.s7p8, lang)}</p>

        <div style={{ margin: '100px 0 80px', padding: '60px 40px', textAlign: 'center', position: 'relative', borderRadius: 20, background: `linear-gradient(135deg, ${C.cyan}0F, ${C.green}0A, ${C.gold}0F)`, border: `1px solid ${C.cyan}26`, overflow: 'hidden' }}>
          <div style={{ position: 'absolute', inset: 0, background: `radial-gradient(ellipse at center, ${C.cyan}1F, transparent 70%)`, pointerEvents: 'none', animation: 'finalePulse 4s ease-in-out infinite' }} />
          <p style={{ fontFamily: "'Playfair Display', serif", fontSize: 'clamp(26px, 4.5vw, 42px)', fontWeight: 900, fontStyle: 'italic', lineHeight: 1.3, color: '#fff', position: 'relative', zIndex: 1, margin: 0 }}>
            {L(t.finA, lang)}{' '}<span style={{ background: `linear-gradient(135deg, ${C.cyan}, ${C.green})`, WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>{L(t.finB, lang)}</span>
          </p>
        </div>

        <div style={{ marginTop: 80, paddingTop: 40, borderTop: '1px solid rgba(255,255,255,0.08)' }}>
          <p style={{ fontSize: 16, color: C.dim, lineHeight: 1.7, fontStyle: 'italic' }}><strong style={{ color: '#fff' }}>Juan Schubert</strong> · {L(t.bio, lang)}</p>
          <div style={{ marginTop: 24, display: 'flex', gap: 12, flexWrap: 'wrap' }}>
            {['#ExtendedHuman', '#DataIsNotTheProblem', '#NegativityBias', '#AIEvolution'].map(tag => (
              <span key={tag} style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 12, padding: '6px 14px', borderRadius: 20, background: `${C.cyan}1A`, color: C.cyan, border: `1px solid ${C.cyan}33` }}>{tag}</span>
            ))}
          </div>
        </div>
      </article>
    </div>
  );
}
