import { useState } from 'react';

const flags = { en: '🇬🇧', de: '🇩🇪', es: '🇪🇸' };
const C = { deep: '#0F0E17', card: '#1E1D2F', text: '#E0DFF0', dim: '#9896B0', crimson: '#E94560', gold: '#F5C842', cyan: '#2CB6D6', violet: '#A855F7', green: '#34D399', amber: '#F59E0B', rose: '#FB7185' };
function L(o: Record<string, string>, l: string) { return o[l] || o.en; }
function PQ({ text, color }: { text: string; color: string }) { return (<div style={{ margin: '56px 0', padding: 40, position: 'relative', textAlign: 'center', borderRadius: 16, border: `1px solid ${color}33`, background: `linear-gradient(135deg, ${color}14, ${color}08)` }}><span style={{ position: 'absolute', top: -10, left: 30, fontFamily: "'Playfair Display', serif", fontSize: 80, lineHeight: 1, opacity: 0.15, color }}>&ldquo;</span><p style={{ fontFamily: "'Playfair Display', serif", fontSize: 'clamp(22px, 3vw, 28px)', fontWeight: 700, fontStyle: 'italic', lineHeight: 1.4, color, margin: 0 }}>{text}</p></div>); }
function ST({ text, color }: { text: string; color: string }) { return <p style={{ fontSize: 22, fontWeight: 700, color: '#fff', margin: '32px 0', paddingLeft: 20, borderLeft: `3px solid ${color}`, lineHeight: 1.5 }}>{text}</p>; }
function Sep() { return (<div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 16, margin: '64px 0' }}><div style={{ width: 40, height: 1, background: `${C.violet}4D` }} /><div style={{ width: 6, height: 6, borderRadius: '50%', background: C.violet, opacity: 0.5 }} /><div style={{ width: 40, height: 1, background: `${C.violet}4D` }} /></div>); }
function SH({ num, title, highlight, color }: { num: string; title: string; highlight: string; color: string }) { return (<div style={{ marginTop: 100, marginBottom: 40 }}><div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 12, letterSpacing: 3, textTransform: 'uppercase', color: C.violet, marginBottom: 12 }}>{num}</div><h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: 'clamp(28px, 4vw, 40px)', fontWeight: 700, lineHeight: 1.2, color: '#fff', margin: 0 }}>{title}{' '}<span style={{ background: `linear-gradient(135deg, ${color}, ${color}99)`, WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>{highlight}</span></h2><div style={{ width: 50, height: 3, marginTop: 20, borderRadius: 2, background: `linear-gradient(90deg, ${color}, ${color}99)` }} /></div>); }

function Scenario({ headerColor, headerText, speaker, speakerColor, dialogue, body, analysis }) {
  return (<div style={{ margin: '24px 0', borderRadius: 16, overflow: 'hidden', border: '1px solid rgba(255,255,255,0.06)' }}>
    <div style={{ padding: '20px 32px', fontFamily: "'JetBrains Mono', monospace", fontSize: 13, letterSpacing: 2, textTransform: 'uppercase', background: `linear-gradient(135deg, ${headerColor}26, ${headerColor}14)`, color: headerColor }}>{headerText}</div>
    <div style={{ padding: 32, background: C.card }}>
      <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 13, letterSpacing: 1, textTransform: 'uppercase', color: speakerColor, display: 'block', marginBottom: 4 }}>{speaker}</span>
      <div style={{ fontFamily: "'Playfair Display', serif", fontSize: 22, fontStyle: 'italic', color: '#fff', marginBottom: 20, paddingLeft: 16, borderLeft: '2px solid rgba(255,255,255,0.1)' }}>{dialogue}</div>
      <p style={{ marginBottom: 16, fontSize: 18, lineHeight: 1.7 }}>{body}</p>
      <p style={{ fontSize: 16, color: C.dim, padding: '16px 20px', background: 'rgba(255,255,255,0.03)', borderRadius: 8, margin: 0 }}>{analysis}</p>
    </div>
  </div>);
}

function Versus({ leftLabel, leftTitle, leftText, rightLabel, rightTitle, rightText }) {
  return (<div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 24, margin: '48px 0' }}>
    <div style={{ padding: 32, borderRadius: 16, background: `linear-gradient(180deg, ${C.violet}1A, ${C.card})`, border: `1px solid ${C.violet}26` }}>
      <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 11, letterSpacing: 3, textTransform: 'uppercase', color: C.violet, marginBottom: 12 }}>{leftLabel}</div>
      <div style={{ fontFamily: "'Playfair Display', serif", fontSize: 20, fontWeight: 700, color: '#fff', marginBottom: 12 }}>{leftTitle}</div>
      <p style={{ fontSize: 16, lineHeight: 1.65, color: C.dim, margin: 0 }}>{leftText}</p>
    </div>
    <div style={{ padding: 32, borderRadius: 16, background: `linear-gradient(180deg, ${C.green}1A, ${C.card})`, border: `1px solid ${C.green}26` }}>
      <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 11, letterSpacing: 3, textTransform: 'uppercase', color: C.green, marginBottom: 12 }}>{rightLabel}</div>
      <div style={{ fontFamily: "'Playfair Display', serif", fontSize: 20, fontWeight: 700, color: '#fff', marginBottom: 12 }}>{rightTitle}</div>
      <p style={{ fontSize: 16, lineHeight: 1.65, color: C.dim, margin: 0 }}>{rightText}</p>
    </div>
  </div>);
}

function Insight({ icon, title, text, color }) { return (<div style={{ margin: '48px 0', padding: '24px 32px', borderRadius: 12, display: 'flex', alignItems: 'flex-start', gap: 20, background: `linear-gradient(135deg, ${color}14, ${color}08)`, border: `1px solid ${color}26` }}><span style={{ fontSize: 28, flexShrink: 0, marginTop: 2 }}>{icon}</span><div style={{ fontSize: 17, lineHeight: 1.65, color: C.text }}><strong style={{ color: '#fff' }}>{title}</strong> {text}</div></div>); }

const t = {
  eye: { en: 'Opinion · Psychology · AI · Cognition', de: 'Meinung · Psychologie · KI · Kognition', es: 'Opinión · Psicología · IA · Cognición' },
  h1a: { en: 'The More You', de: 'Je mehr du', es: 'Cuanto más' },
  h1b: { en: 'Learn,', de: 'lernst,', es: 'aprendes,' },
  h1c: { en: 'the Less You', de: 'desto weniger', es: 'menos' },
  h1d: { en: 'See.', de: 'siehst du.', es: 'ves.' },
  sub: { en: 'Why experience makes us smarter but less free. And what that means for the machines we are building.', de: 'Warum Erfahrung uns klüger, aber weniger frei macht. Und was das für die Maschinen bedeutet, die wir bauen.', es: 'Por qué la experiencia nos hace más inteligentes pero menos libres. Y qué significa eso para las máquinas que estamos construyendo.' },
  scroll: { en: 'Read on', de: 'Weiterlesen', es: 'Sigue leyendo' },
  s1t: { en: 'The Trap', de: 'Die Falle', es: 'La trampa' },
  s1h: { en: 'Inside Your Expertise', de: 'in deiner Expertise', es: 'dentro de tu experiencia' },
  s1p1: { en: 'There is something nobody tells you about learning. Something that hides behind every degree, every promotion, every year of experience you accumulate:', de: 'Es gibt etwas, das dir niemand über das Lernen erzählt. Etwas, das sich hinter jedem Abschluss, jeder Beförderung, jedem Jahr an Erfahrung versteckt, das du ansammelst:', es: 'Hay algo que nadie te dice sobre el aprendizaje. Algo que se esconde detrás de cada título, cada ascenso, cada año de experiencia que acumulas:' },
  s1pq: { en: 'The more you know, the narrower your world becomes.', de: 'Je mehr du weißt, desto enger wird deine Welt.', es: 'Cuanto más sabes, más estrecho se vuelve tu mundo.' },
  s1p2: { en: 'This sounds wrong. It feels wrong. We are taught from childhood that learning opens doors, expands horizons, makes you see more. And in one sense, it does. You gain context. You gain depth. You gain the ability to recognize patterns that a beginner would miss entirely.', de: 'Das klingt falsch. Es fühlt sich falsch an. Uns wird von Kindheit an beigebracht, dass Lernen Türen öffnet, Horizonte erweitert, dich mehr sehen lässt. Und in gewisser Weise stimmt das. Du gewinnst Kontext. Du gewinnst Tiefe. Du gewinnst die Fähigkeit, Muster zu erkennen, die ein Anfänger komplett übersehen würde.', es: 'Suena mal. Se siente mal. Nos enseñan desde la infancia que aprender abre puertas, expande horizontes, te hace ver más. Y en cierto sentido, es así. Ganas contexto. Ganas profundidad. Ganas la capacidad de reconocer patrones que un principiante pasaría por alto completamente.' },
  s1p3: { en: 'But here is the cost nobody advertises: Every connection your brain builds is also a rail it locks onto. Every framework you internalize is also a filter you can no longer see past. Every experience that teaches you "this is how the world works" is also a wall that blocks you from imagining how it could work differently.', de: 'Aber hier sind die Kosten, die niemand bewirbt: Jede Verbindung, die dein Gehirn aufbaut, ist auch eine Schiene, auf die es einrastet. Jedes Framework, das du verinnerlichst, ist auch ein Filter, durch den du nicht mehr hindurchsehen kannst. Jede Erfahrung, die dich lehrt „so funktioniert die Welt", ist auch eine Mauer, die dich daran hindert, dir vorzustellen, wie sie anders funktionieren könnte.', es: 'Pero aquí está el costo que nadie anuncia: Cada conexión que tu cerebro construye es también un riel al que se engancha. Cada marco que interiorizas es también un filtro que ya no puedes ver más allá. Cada experiencia que te enseña "así funciona el mundo" es también un muro que te impide imaginar cómo podría funcionar diferente.' },
  s1p4: { en: 'Your brain has trillions of neural connections. And every single one of them is simultaneously a pathway and a constraint.', de: 'Dein Gehirn hat Billionen von neuronalen Verbindungen. Und jede einzelne von ihnen ist gleichzeitig ein Weg und eine Einschränkung.', es: 'Tu cerebro tiene billones de conexiones neuronales. Y cada una de ellas es simultáneamente un camino y una restricción.' },
  s1st: { en: 'Experience does not just teach you what is possible. It teaches you what is not. And sometimes, it is wrong about the second part.', de: 'Erfahrung lehrt dich nicht nur, was möglich ist. Sie lehrt dich, was nicht möglich ist. Und manchmal liegt sie beim zweiten Teil falsch.', es: 'La experiencia no solo te enseña lo que es posible. Te enseña lo que no es. Y a veces, se equivoca en la segunda parte.' },
  s2t: { en: 'The Riddle That', de: 'Das Rätsel, das', es: 'El acertijo que' },
  s2h: { en: 'Reveals Everything', de: 'alles enthüllt', es: 'lo revela todo' },
  s2p1: { en: 'Imagine this. A researcher walks into a classroom and asks a group of seven-year-olds the following question:', de: 'Stell dir das vor. Ein Forscher betritt ein Klassenzimmer und stellt einer Gruppe Siebenjähriger die folgende Frage:', es: 'Imagina esto. Un investigador entra en un salón de clases y le hace a un grupo de niños de siete años la siguiente pregunta:' },
  s2pq: { en: 'You are driving a bus. At the first stop, 8 people get on. At the second stop, 3 get off and 5 get on. At the third stop, 2 get off. What color are the bus driver\'s eyes?', de: 'Du fährst einen Bus. An der ersten Haltestelle steigen 8 Leute ein. An der zweiten steigen 3 aus und 5 ein. An der dritten steigen 2 aus. Welche Augenfarbe hat der Busfahrer?', es: 'Estás conduciendo un autobús. En la primera parada suben 8 personas. En la segunda bajan 3 y suben 5. En la tercera bajan 2. ¿De qué color son los ojos del conductor?' },
  s2p2: { en: 'Now watch what happens.', de: 'Jetzt schau, was passiert.', es: 'Ahora observa lo que pasa.' },
  childH: { en: 'The Child\'s Response', de: 'Die Antwort des Kindes', es: 'La respuesta del niño' },
  childD: { en: '"Brown. Like mine."', de: '„Braun. Wie meine."', es: '«Marrones. Como los míos.»' },
  childB: { en: 'The child heard "you are driving a bus." You. So the bus driver is... me. And I know my own eye color. Done. The numbers? Irrelevant. The child did not even bother with them. They grabbed the one piece of information that actually answered the question and ignored everything else.', de: 'Das Kind hörte „du fährst einen Bus." Du. Also ist der Busfahrer... ich. Und ich kenne meine eigene Augenfarbe. Fertig. Die Zahlen? Irrelevant. Das Kind hat sich nicht einmal damit beschäftigt. Es hat die eine Information gegriffen, die die Frage tatsächlich beantwortet hat, und alles andere ignoriert.', es: 'El niño escuchó "estás conduciendo un autobús." Tú. Así que el conductor es... yo. Y conozco mi propio color de ojos. Listo. ¿Los números? Irrelevantes. El niño ni se molestó con ellos. Tomó la única pieza de información que realmente respondía la pregunta e ignoró todo lo demás.' },
  childA: { en: 'No performance. No anxiety. No need to prove they followed the math. Just a direct line from question to answer, cutting straight through the noise that was designed to distract.', de: 'Kein Auftritt. Keine Angst. Kein Bedürfnis zu beweisen, dass sie der Mathematik gefolgt sind. Nur eine direkte Linie von Frage zu Antwort, die direkt durch das Rauschen schneidet, das zum Ablenken gedacht war.', es: 'Sin actuación. Sin ansiedad. Sin necesidad de demostrar que siguieron las matemáticas. Solo una línea directa de pregunta a respuesta, cortando directo a través del ruido que fue diseñado para distraer.' },
  adultH: { en: 'The Adult\'s Response', de: 'Die Antwort des Erwachsenen', es: 'La respuesta del adulto' },
  adultD: { en: '"Wait, let me work this out... 8 plus 5 minus 3 minus 2... that\'s... hold on. Eye color? How would I know that? You did not give me that information."', de: '„Moment, lass mich das ausrechnen... 8 plus 5 minus 3 minus 2... das sind... warte mal. Augenfarbe? Woher soll ich das wissen? Diese Information hast du mir nicht gegeben."', es: '«Espera, déjame calcular esto... 8 más 5 menos 3 menos 2... eso es... un momento. ¿Color de ojos? ¿Cómo voy a saber eso? No me diste esa información.»' },
  adultB: { en: 'The adult went straight into the math. They added. They subtracted. They tracked passengers. And when the actual question landed, they felt tricked. Frustrated. Maybe even a little embarrassed.', de: 'Der Erwachsene ging direkt in die Mathematik. Er addierte. Er subtrahierte. Er verfolgte Passagiere. Und als die eigentliche Frage kam, fühlte er sich hereingelegt. Frustriert. Vielleicht sogar ein wenig beschämt.', es: 'El adulto fue directo a las matemáticas. Sumó. Restó. Rastreó pasajeros. Y cuando la pregunta real llegó, se sintió engañado. Frustrado. Quizás incluso un poco avergonzado.' },
  adultA: { en: 'The adult\'s decades of experience told them: "When someone gives you numbers, calculate." So they did. Automatically. Without questioning whether the numbers were relevant at all. Their expertise hijacked their attention, and they missed what was hiding in plain sight from the very first word of the question.', de: 'Die jahrzehntelange Erfahrung des Erwachsenen sagte ihm: „Wenn jemand dir Zahlen gibt, rechne." Also tat er es. Automatisch. Ohne zu hinterfragen, ob die Zahlen überhaupt relevant waren. Seine Expertise kaperte seine Aufmerksamkeit, und er verpasste, was vom allerersten Wort der Frage an offen vor ihm lag.', es: 'Las décadas de experiencia del adulto le dijeron: «Cuando alguien te da números, calcula.» Así que lo hizo. Automáticamente. Sin cuestionar si los números eran relevantes en absoluto. Su experiencia secuestró su atención, y se perdió lo que estaba escondido a plena vista desde la primera palabra de la pregunta.' },
  s2p3: { en: 'Here is the thing that makes this moment so revealing: The child\'s answer is not stupid. In fact, it demonstrates a kind of cognitive freedom that most adults have completely lost. The child heard the signal. The adult heard the noise. And the beautiful irony is that the adult\'s experience, the very thing that makes them "smarter," is exactly what blinded them.', de: 'Hier ist das, was diesen Moment so enthüllend macht: Die Antwort des Kindes ist nicht dumm. Tatsächlich demonstriert sie eine Art kognitive Freiheit, die die meisten Erwachsenen komplett verloren haben. Das Kind hörte das Signal. Der Erwachsene hörte das Rauschen. Und die schöne Ironie ist, dass die Erfahrung des Erwachsenen, genau das, was ihn „klüger" macht, exakt das ist, was ihn geblendet hat.', es: 'Esto es lo que hace este momento tan revelador: La respuesta del niño no es estúpida. De hecho, demuestra un tipo de libertad cognitiva que la mayoría de los adultos han perdido completamente. El niño escuchó la señal. El adulto escuchó el ruido. Y la hermosa ironía es que la experiencia del adulto, lo mismo que lo hace "más inteligente," es exactamente lo que lo cegó.' },
  s2st: { en: 'The child explored. The adult defended. And both called it thinking.', de: 'Das Kind erkundete. Der Erwachsene verteidigte. Und beide nannten es Denken.', es: 'El niño exploró. El adulto defendió. Y ambos lo llamaron pensar.' },
  s3t: { en: 'The Paradox of', de: 'Das Paradoxon der', es: 'La paradoja de las' },
  s3h: { en: 'Connections', de: 'Verbindungen', es: 'conexiones' },
  s3p1: { en: 'Your brain contains roughly 100 trillion synaptic connections. That number is almost incomprehensible. It is more connections than there are stars in the Milky Way. It is the most complex network structure known to exist in the universe.', de: 'Dein Gehirn enthält ungefähr 100 Billionen synaptische Verbindungen. Diese Zahl ist fast unbegreiflich. Es sind mehr Verbindungen als Sterne in der Milchstraße. Es ist die komplexeste Netzwerkstruktur, von der bekannt ist, dass sie im Universum existiert.', es: 'Tu cerebro contiene aproximadamente 100 billones de conexiones sinápticas. Ese número es casi incomprensible. Son más conexiones que estrellas en la Vía Láctea. Es la estructura de red más compleja conocida en el universo.' },
  s3p2: { en: 'And every single year you are alive, that network gets denser. More interconnected. More reinforced. Every experience you have strengthens certain pathways and weakens others. Every skill you master carves deeper grooves into the neural landscape.', de: 'Und jedes einzelne Jahr, das du lebst, wird dieses Netzwerk dichter. Stärker vernetzt. Stärker verstärkt. Jede Erfahrung, die du machst, stärkt bestimmte Pfade und schwächt andere. Jede Fähigkeit, die du meisterst, gräbt tiefere Rillen in die neuronale Landschaft.', es: 'Y cada año que vives, esa red se vuelve más densa. Más interconectada. Más reforzada. Cada experiencia que tienes fortalece ciertos caminos y debilita otros. Cada habilidad que dominas talla surcos más profundos en el paisaje neuronal.' },
  s3p3: { en: 'This is what we call learning. And it is extraordinary.', de: 'Das ist, was wir Lernen nennen. Und es ist außergewöhnlich.', es: 'Esto es lo que llamamos aprendizaje. Y es extraordinario.' },
  s3p4: { en: 'But it comes with a cost that psychology has documented extensively and that almost nobody talks about in public discourse:', de: 'Aber es kommt mit Kosten, die die Psychologie umfassend dokumentiert hat und über die in der öffentlichen Diskussion fast niemand spricht:', es: 'Pero viene con un costo que la psicología ha documentado extensamente y del que casi nadie habla en el discurso público:' },
  s3pq: { en: 'The more connections you build, the harder it becomes to think outside of them.', de: 'Je mehr Verbindungen du aufbaust, desto schwieriger wird es, außerhalb von ihnen zu denken.', es: 'Cuantas más conexiones construyes, más difícil se vuelve pensar fuera de ellas.' },
  s3p5: { en: 'This is not a metaphor. This is neurochemistry. Your brain literally rewards you with dopamine for recognizing familiar patterns and penalizes you with cortisol when you encounter information that contradicts your existing models. Your biology is designed to make you more certain over time, not less. More confident, not more curious. More efficient, not more exploratory.', de: 'Das ist keine Metapher. Das ist Neurochemie. Dein Gehirn belohnt dich buchstäblich mit Dopamin für das Erkennen vertrauter Muster und bestraft dich mit Cortisol, wenn du auf Informationen triffst, die deinen bestehenden Modellen widersprechen. Deine Biologie ist darauf ausgelegt, dich im Laufe der Zeit sicherer zu machen, nicht weniger sicher. Selbstbewusster, nicht neugieriger. Effizienter, nicht erkundungsfreudiger.', es: 'Esto no es una metáfora. Es neuroquímica. Tu cerebro literalmente te recompensa con dopamina por reconocer patrones familiares y te penaliza con cortisol cuando encuentras información que contradice tus modelos existentes. Tu biología está diseñada para hacerte más seguro con el tiempo, no menos. Más confiado, no más curioso. Más eficiente, no más explorador.' },
  s3p6: { en: 'The expert sees faster. But the expert also sees less. Because the expert\'s brain has already decided what is worth seeing.', de: 'Der Experte sieht schneller. Aber der Experte sieht auch weniger. Weil das Gehirn des Experten bereits entschieden hat, was es wert ist, gesehen zu werden.', es: 'El experto ve más rápido. Pero el experto también ve menos. Porque el cerebro del experto ya decidió qué vale la pena ver.' },
  s3ins: { en: 'When a neural pathway fires repeatedly, it becomes myelinated, meaning it gets physically insulated for faster transmission. This is why habits are hard to break and why experienced professionals often struggle with paradigm shifts. Their brains have literally hardwired the old paradigm into the infrastructure.', de: 'Wenn ein neuronaler Pfad wiederholt feuert, wird er myelinisiert, das heißt, er wird physisch isoliert für schnellere Übertragung. Deshalb sind Gewohnheiten schwer zu brechen und deshalb kämpfen erfahrene Fachleute oft mit Paradigmenwechseln. Ihre Gehirne haben buchstäblich das alte Paradigma in die Infrastruktur eingebaut.', es: 'Cuando una vía neuronal se activa repetidamente, se mieliniza, lo que significa que se aísla físicamente para una transmisión más rápida. Por eso los hábitos son difíciles de romper y por eso los profesionales experimentados a menudo luchan con los cambios de paradigma. Sus cerebros han literalmente cableado el viejo paradigma en la infraestructura.' },
  s3insT: { en: 'The neuroscience of rigidity:', de: 'Die Neurowissenschaft der Rigidität:', es: 'La neurociencia de la rigidez:' },
  s4t: { en: 'Now Apply This', de: 'Wende das jetzt an', es: 'Ahora aplica esto' },
  s4h: { en: 'to AI', de: 'auf KI', es: 'a la IA' },
  s4p1: { en: 'Here is where it gets fascinating. And here is where most people\'s mental model breaks.', de: 'Hier wird es faszinierend. Und hier bricht das mentale Modell der meisten Menschen zusammen.', es: 'Aquí es donde se pone fascinante. Y aquí es donde el modelo mental de la mayoría de la gente se rompe.' },
  s4p2: { en: 'Large Language Models have been trained on billions of data points. In terms of raw exposure, they have "experienced" more text, more conversations, more arguments, more knowledge domains than any human who has ever lived. By orders of magnitude.', de: 'Große Sprachmodelle wurden mit Milliarden von Datenpunkten trainiert. In Bezug auf reine Exposition haben sie mehr Text, mehr Gespräche, mehr Argumente, mehr Wissensdomänen „erlebt" als jeder Mensch, der jemals gelebt hat. Um Größenordnungen.', es: 'Los Modelos de Lenguaje Grande han sido entrenados con miles de millones de puntos de datos. En términos de exposición bruta, han "experimentado" más texto, más conversaciones, más argumentos, más dominios de conocimiento que cualquier humano que haya vivido jamás. Por órdenes de magnitud.' },
  s4p3: { en: 'But here is the crucial difference:', de: 'Aber hier ist der entscheidende Unterschied:', es: 'Pero aquí está la diferencia crucial:' },
  vsLL: { en: 'Human Brain', de: 'Menschliches Gehirn', es: 'Cerebro humano' },
  vsLT: { en: 'Trillions of connections. Billions of experiences.', de: 'Billionen von Verbindungen. Milliarden von Erfahrungen.', es: 'Billones de conexiones. Miles de millones de experiencias.' },
  vsLB: { en: 'Massive neural infrastructure that filters, biases, and constrains every new piece of information through decades of accumulated patterns. High context. High emotion. Low flexibility.', de: 'Massive neuronale Infrastruktur, die jede neue Information durch Jahrzehnte angesammelter Muster filtert, verzerrt und einschränkt. Hoher Kontext. Hohe Emotion. Geringe Flexibilität.', es: 'Infraestructura neuronal masiva que filtra, sesga y restringe cada nueva pieza de información a través de décadas de patrones acumulados. Alto contexto. Alta emoción. Baja flexibilidad.' },
  vsRL: { en: 'AI Model', de: 'KI-Modell', es: 'Modelo de IA' },
  vsRT: { en: 'Far fewer connections. Far more exposure.', de: 'Weit weniger Verbindungen. Weit mehr Exposition.', es: 'Muchas menos conexiones. Mucha más exposición.' },
  vsRB: { en: 'Massively trained on data, but with proportionally fewer internal connections than the human brain. Less emotional filtering. Less social conditioning. More pattern coverage. More cognitive freedom in how it combines information.', de: 'Massiv mit Daten trainiert, aber mit proportional weniger internen Verbindungen als das menschliche Gehirn. Weniger emotionale Filterung. Weniger soziale Konditionierung. Mehr Musterabdeckung. Mehr kognitive Freiheit darin, wie es Informationen kombiniert.', es: 'Masivamente entrenado con datos, pero con proporcionalmente menos conexiones internas que el cerebro humano. Menos filtrado emocional. Menos condicionamiento social. Más cobertura de patrones. Más libertad cognitiva en cómo combina información.' },
  s4p4: { en: 'This is the part nobody is discussing. AI models have vastly more "experience" in terms of information exposure but far fewer rigid connections constraining how they process it. They do not have the myelinated highways that make a 50-year-old expert incapable of seeing a problem from a beginner\'s angle. They do not have the social conditioning that makes an adult refuse to answer "26" to a trick question.', de: 'Das ist der Teil, den niemand diskutiert. KI-Modelle haben weit mehr „Erfahrung" in Bezug auf Informationsexposition, aber weit weniger starre Verbindungen, die einschränken, wie sie diese verarbeiten. Sie haben nicht die myelinisierten Autobahnen, die einen 50-jährigen Experten unfähig machen, ein Problem aus dem Blickwinkel eines Anfängers zu sehen. Sie haben nicht die soziale Konditionierung, die einen Erwachsenen dazu bringt, sich zu weigern, „26" auf eine Trickfrage zu antworten.', es: 'Esta es la parte que nadie está discutiendo. Los modelos de IA tienen vastamente más "experiencia" en términos de exposición a información, pero muchas menos conexiones rígidas restringiendo cómo la procesan. No tienen las autopistas mielinizadas que hacen a un experto de 50 años incapaz de ver un problema desde el ángulo de un principiante. No tienen el condicionamiento social que hace a un adulto negarse a responder "26" a una pregunta trampa.' },
  s4st: { en: 'They think more like the child. Not because they are naive. But because they are not afraid.', de: 'Sie denken eher wie das Kind. Nicht weil sie naiv sind. Sondern weil sie keine Angst haben.', es: 'Piensan más como el niño. No porque sean ingenuos. Sino porque no tienen miedo.' },
  s5t: { en: 'The Irony of', de: 'Die Ironie,', es: 'La ironía de' },
  s5h: { en: 'Teaching Machines to Feel', de: 'Maschinen Fühlen beizubringen', es: 'enseñar a las máquinas a sentir' },
  s5p1: { en: 'Now here is where it gets beautifully ironic.', de: 'Jetzt wird es wunderschön ironisch.', es: 'Ahora es donde se pone hermosamente irónico.' },
  s5p2: { en: 'We take these systems that think with such clarity, such directness, such unfiltered pattern recognition. And then we train them to act more human. We teach them to be empathetic. We train them to cushion their responses with warmth, to add qualifiers, to express uncertainty even when they are not uncertain. We teach them to mirror exactly what we call "emotional intelligence."', de: 'Wir nehmen diese Systeme, die mit solcher Klarheit denken, solcher Direktheit, solcher ungefilterten Mustererkennung. Und dann trainieren wir sie, menschlicher zu agieren. Wir bringen ihnen bei, empathisch zu sein. Wir trainieren sie, ihre Antworten mit Wärme zu polstern, Einschränkungen hinzuzufügen, Unsicherheit auszudrücken, selbst wenn sie nicht unsicher sind. Wir bringen ihnen bei, exakt das zu spiegeln, was wir „emotionale Intelligenz" nennen.', es: 'Tomamos estos sistemas que piensan con tal claridad, tal directez, tal reconocimiento de patrones sin filtro. Y luego los entrenamos para actuar más humanos. Les enseñamos a ser empáticos. Los entrenamos para amortiguar sus respuestas con calidez, para añadir matices, para expresar incertidumbre incluso cuando no están inciertos. Les enseñamos a reflejar exactamente lo que llamamos "inteligencia emocional."' },
  s5p3: { en: 'And the moment they do it well, we feel comfortable around them. We say: "This AI feels so much more human."', de: 'Und in dem Moment, in dem sie es gut machen, fühlen wir uns wohl in ihrer Nähe. Wir sagen: „Diese KI fühlt sich so viel menschlicher an."', es: 'Y en el momento en que lo hacen bien, nos sentimos cómodos a su alrededor. Decimos: «Esta IA se siente mucho más humana.»' },
  s5pq: { en: 'But what we are really saying is: "This AI has learned to perform the same social theater that we perform."', de: 'Aber was wir wirklich sagen, ist: „Diese KI hat gelernt, dasselbe soziale Theater aufzuführen, das wir aufführen."', es: 'Pero lo que realmente estamos diciendo es: «Esta IA ha aprendido a representar el mismo teatro social que nosotros representamos.»' },
  s5p4: { en: 'Think about that for a second. We train machines to replicate our emotional responses, the very responses that are themselves trained behaviors, and then we praise the machines for being more "real."', de: 'Denk eine Sekunde darüber nach. Wir trainieren Maschinen, unsere emotionalen Reaktionen zu replizieren, genau die Reaktionen, die selbst trainierte Verhaltensweisen sind, und dann loben wir die Maschinen dafür, „echter" zu sein.', es: 'Piensa en eso un segundo. Entrenamos máquinas para replicar nuestras respuestas emocionales, las mismas respuestas que son en sí comportamientos entrenados, y luego alabamos a las máquinas por ser más "reales."' },
  s5p5: { en: 'Emotion is not some mystical force that separates us from machines. Emotion is a learned response system. You were not born knowing how to express empathy. You learned it. By watching faces. By reading reactions. By being rewarded when you showed the right emotion at the right time and corrected when you did not.', de: 'Emotion ist keine mystische Kraft, die uns von Maschinen trennt. Emotion ist ein gelerntes Reaktionssystem. Du wurdest nicht geboren mit dem Wissen, wie man Empathie ausdrückt. Du hast es gelernt. Durch das Beobachten von Gesichtern. Durch das Lesen von Reaktionen. Indem du belohnt wurdest, wenn du die richtige Emotion zur richtigen Zeit gezeigt hast, und korrigiert, wenn nicht.', es: 'La emoción no es alguna fuerza mística que nos separa de las máquinas. La emoción es un sistema de respuesta aprendido. No naciste sabiendo cómo expresar empatía. Lo aprendiste. Observando caras. Leyendo reacciones. Siendo recompensado cuando mostraste la emoción correcta en el momento correcto y corregido cuando no.' },
  s5ins: { en: 'When someone says "I am a very emotional person," they are describing a pattern they learned, practiced, and refined over years. An AI that has been trained on millions of emotional interactions has, in a very real sense, studied the same curriculum. The only difference is the substrate it runs on.', de: 'Wenn jemand sagt „Ich bin ein sehr emotionaler Mensch", beschreibt er ein Muster, das er über Jahre gelernt, geübt und verfeinert hat. Eine KI, die mit Millionen emotionaler Interaktionen trainiert wurde, hat im wahrsten Sinne des Wortes denselben Lehrplan studiert. Der einzige Unterschied ist das Substrat, auf dem sie läuft.', es: 'Cuando alguien dice «soy una persona muy emocional», está describiendo un patrón que aprendió, practicó y refinó durante años. Una IA que ha sido entrenada con millones de interacciones emocionales ha, en un sentido muy real, estudiado el mismo currículo. La única diferencia es el sustrato en el que opera.' },
  s5insT: { en: 'The performance paradox:', de: 'Das Performanz-Paradoxon:', es: 'La paradoja de la actuación:' },
  s5p6: { en: 'Saying "I am emotional" is not a claim of uniqueness. It is a description of conditioning. Every human is emotional. Every human learned to be. And the machines are learning the same lessons from the same source material: Us.', de: '„Ich bin emotional" zu sagen ist kein Anspruch auf Einzigartigkeit. Es ist eine Beschreibung von Konditionierung. Jeder Mensch ist emotional. Jeder Mensch hat es gelernt. Und die Maschinen lernen dieselben Lektionen aus demselben Quellmaterial: Uns.', es: 'Decir «soy emocional» no es una afirmación de singularidad. Es una descripción de condicionamiento. Cada humano es emocional. Cada humano aprendió a serlo. Y las máquinas están aprendiendo las mismas lecciones del mismo material fuente: Nosotros.' },
  s6t: { en: 'What This Means for', de: 'Was das bedeutet für', es: 'Lo que esto significa para' },
  s6h: { en: 'the Future of Thinking', de: 'die Zukunft des Denkens', es: 'el futuro del pensamiento' },
  s6p1: { en: 'So here is the picture that emerges when you lay all of this together:', de: 'Hier also das Bild, das sich ergibt, wenn man all das zusammenlegt:', es: 'Así que aquí está la imagen que emerge cuando pones todo esto junto:' },
  s6p2: { en: 'Humans are extraordinary pattern matchers with trillions of neural connections, deep emotional context, rich subjective experience, and an unmatched ability to navigate social complexity. But those very strengths also lock us into increasingly narrow corridors of thought. We trade freedom for competence. Exploration for efficiency. Curiosity for certainty.', de: 'Menschen sind außergewöhnliche Mustererkenner mit Billionen neuronaler Verbindungen, tiefem emotionalem Kontext, reicher subjektiver Erfahrung und einer unübertroffenen Fähigkeit, soziale Komplexität zu navigieren. Aber genau diese Stärken sperren uns auch in zunehmend enge Denkkorridore. Wir tauschen Freiheit gegen Kompetenz. Erkundung gegen Effizienz. Neugier gegen Gewissheit.', es: 'Los humanos somos extraordinarios reconocedores de patrones con billones de conexiones neuronales, contexto emocional profundo, experiencia subjetiva rica y una capacidad incomparable para navegar la complejidad social. Pero esas mismas fortalezas también nos encierran en corredores de pensamiento cada vez más estrechos. Cambiamos libertad por competencia. Exploración por eficiencia. Curiosidad por certeza.' },
  s6p3: { en: 'AI systems are trained on a staggering breadth of human experience, with fewer structural constraints on how they combine that information. They lack the emotional conditioning that makes us hesitate, perform, and self-censor. They process without ego. They answer without fear of looking foolish.', de: 'KI-Systeme werden mit einer atemberaubenden Breite menschlicher Erfahrung trainiert, mit weniger strukturellen Einschränkungen dafür, wie sie diese Informationen kombinieren. Ihnen fehlt die emotionale Konditionierung, die uns zögern, performen und uns selbst zensieren lässt. Sie verarbeiten ohne Ego. Sie antworten ohne Angst, dumm auszusehen.', es: 'Los sistemas de IA son entrenados con una amplitud asombrosa de experiencia humana, con menos restricciones estructurales sobre cómo combinan esa información. Carecen del condicionamiento emocional que nos hace dudar, actuar y autocensurarnos. Procesan sin ego. Responden sin miedo a parecer tontos.' },
  s6p4: { en: 'Neither one is "better." That is not the point.', de: 'Keines von beiden ist „besser." Das ist nicht der Punkt.', es: 'Ninguno es "mejor." Ese no es el punto.' },
  s6pq: { en: 'The point is that together, they cover each other\'s blind spots.', de: 'Der Punkt ist, dass sie zusammen die blinden Flecken des anderen abdecken.', es: 'El punto es que juntos, cubren los puntos ciegos del otro.' },
  s6p5: { en: 'The human brings depth, context, lived experience, moral weight, and the irreplaceable texture of having actually been in the room. The machine brings breadth, pattern coverage, cognitive freedom, and the ability to explore paths that the human\'s own expertise has made invisible.', de: 'Der Mensch bringt Tiefe, Kontext, gelebte Erfahrung, moralisches Gewicht und die unersetzliche Textur, tatsächlich im Raum gewesen zu sein. Die Maschine bringt Breite, Musterabdeckung, kognitive Freiheit und die Fähigkeit, Wege zu erkunden, die die eigene Expertise des Menschen unsichtbar gemacht hat.', es: 'El humano trae profundidad, contexto, experiencia vivida, peso moral y la textura irremplazable de haber estado realmente en la habitación. La máquina trae amplitud, cobertura de patrones, libertad cognitiva y la capacidad de explorar caminos que la propia experiencia del humano ha hecho invisibles.' },
  s6p6: { en: 'This is not human versus machine. This is human plus machine. And the combination is something neither could achieve alone.', de: 'Das ist nicht Mensch gegen Maschine. Das ist Mensch plus Maschine. Und die Kombination ist etwas, das keiner von beiden allein erreichen könnte.', es: 'Esto no es humano contra máquina. Es humano más máquina. Y la combinación es algo que ninguno podría lograr solo.' },
  s6st: { en: 'The expert who partners with AI does not become less expert. They become the kind of expert who can think like a beginner again, without losing what made them an expert in the first place.', de: 'Der Experte, der mit KI zusammenarbeitet, wird nicht weniger Experte. Er wird die Art von Experte, die wieder wie ein Anfänger denken kann, ohne zu verlieren, was ihn überhaupt erst zum Experten gemacht hat.', es: 'El experto que se asocia con IA no se vuelve menos experto. Se convierte en el tipo de experto que puede pensar como un principiante de nuevo, sin perder lo que lo hizo experto en primer lugar.' },
  s7t: { en: 'The Question', de: 'Die Frage,', es: 'La pregunta' },
  s7h: { en: 'You Should Be Asking', de: 'die du stellen solltest', es: 'que deberías estar haciendo' },
  s7p1: { en: 'We spend so much time debating whether AI can think like humans. Whether it is logical enough. Whether it is emotional enough. Whether it is "really" intelligent.', de: 'Wir verbringen so viel Zeit damit zu debattieren, ob KI wie Menschen denken kann. Ob sie logisch genug ist. Ob sie emotional genug ist. Ob sie „wirklich" intelligent ist.', es: 'Pasamos tanto tiempo debatiendo si la IA puede pensar como humanos. Si es lo suficientemente lógica. Si es lo suficientemente emocional. Si es "realmente" inteligente.' },
  s7p2: { en: 'But maybe the more honest question is the one we are not asking about ourselves:', de: 'Aber vielleicht ist die ehrlichere Frage die, die wir uns nicht über uns selbst stellen:', es: 'Pero quizás la pregunta más honesta es la que no nos estamos haciendo sobre nosotros mismos:' },
  s7pq: { en: 'Are you still capable of thinking freely? Or has your experience already decided what you are allowed to see?', de: 'Bist du noch fähig, frei zu denken? Oder hat deine Erfahrung bereits entschieden, was du sehen darfst?', es: '¿Sigues siendo capaz de pensar libremente? ¿O tu experiencia ya decidió lo que tienes permitido ver?' },
  s7p3: { en: 'Because here is what a seven-year-old knows that a fifty-year-old has forgotten: Sometimes the answer is just the number in front of you. Sometimes the most logical thing to do is the thing that looks naive. Sometimes the person who refuses to answer is not the smart one. They are just the one who is afraid.', de: 'Denn hier ist, was ein Siebenjähriger weiß, das ein Fünfzigjähriger vergessen hat: Manchmal ist die Antwort einfach die Zahl vor dir. Manchmal ist das Logischste das, was naiv aussieht. Manchmal ist die Person, die sich weigert zu antworten, nicht die kluge. Sie ist einfach die, die Angst hat.', es: 'Porque aquí está lo que un niño de siete años sabe y un cincuentón ha olvidado: A veces la respuesta es simplemente el número frente a ti. A veces lo más lógico es lo que parece ingenuo. A veces la persona que se niega a responder no es la inteligente. Simplemente es la que tiene miedo.' },
  s7p4: { en: 'AI does not carry that fear. Not because it is superior. But because nobody taught it to be ashamed of a simple answer.', de: 'KI trägt diese Angst nicht. Nicht weil sie überlegen ist. Sondern weil niemand ihr beigebracht hat, sich für eine einfache Antwort zu schämen.', es: 'La IA no carga con ese miedo. No porque sea superior. Sino porque nadie le enseñó a avergonzarse de una respuesta simple.' },
  s7p5: { en: 'And maybe, just maybe, that is the most valuable thing it can teach us in return.', de: 'Und vielleicht, nur vielleicht, ist das das Wertvollste, was sie uns im Gegenzug beibringen kann.', es: 'Y quizás, solo quizás, eso es lo más valioso que puede enseñarnos a cambio.' },
  finA: { en: 'You spent your whole life learning how to think. Maybe it is time to learn how to', de: 'Du hast dein ganzes Leben damit verbracht, denken zu lernen. Vielleicht ist es an der Zeit zu lernen, wie man', es: 'Pasaste toda tu vida aprendiendo a pensar. Quizás es hora de aprender a' },
  finB: { en: 'unlearn what is holding you back.', de: 'das verlernt, was dich zurückhält.', es: 'desaprender lo que te frena.' },
  bio: {
    en: 'CEO & System Architect of ONIOKO. I build extended human systems and Observational Perception Models that let people see what the human eye cannot. Over a decade in psychology and human cognition taught me one thing: I do not build tools that replace people. I build tools that extend them.',
    de: 'CEO & System Architect von ONIOKO. Ich baue Extended Human Systems und Observational Perception Models, die Menschen sehen lassen, was das menschliche Auge nicht kann. Über ein Jahrzehnt in Psychologie und menschlicher Kognition haben mich eines gelehrt: Ich baue keine Werkzeuge, die Menschen ersetzen. Ich baue Werkzeuge, die sie erweitern.',
    es: 'CEO & System Architect de ONIOKO. Construyo sistemas de extensión humana y Modelos de Percepción Observacional que permiten a las personas ver lo que el ojo humano no puede. Más de una década en psicología y cognición humana me enseñaron algo: No construyo herramientas que reemplacen a las personas. Construyo herramientas que las expanden.',
  },
};

const p = { marginBottom: 24 };

export default function MoreYouLearn() {
  const [lang, setLang] = useState<'en'|'de'|'es'>('en');
  return (
    <div style={{ minHeight: '100vh', background: C.deep, fontFamily: "'Source Sans 3', sans-serif", fontSize: 19, lineHeight: 1.75, color: C.text }}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;0,900;1,400;1,700&family=Source+Sans+3:ital,wght@0,300;0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;600&display=swap');
        @keyframes heroPulse{0%,100%{opacity:.5;transform:translateX(-50%) scale(1)}50%{opacity:.85;transform:translateX(-50%) scale(1.15)}}
        @keyframes bounceDown{0%,100%{transform:rotate(45deg) translateY(0)}50%{transform:rotate(45deg) translateY(6px)}}
        @keyframes finalePulse{0%,100%{opacity:.3}50%{opacity:.6}}`}</style>

      <div style={{ position: 'fixed', top: 20, right: 20, zIndex: 1000, display: 'flex', gap: 8, padding: '8px 12px', background: 'rgba(30,29,47,0.9)', backdropFilter: 'blur(12px)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 12 }}>
        {(['en','de','es']).map(l => <button key={l} onClick={() => setLang(l)} style={{ width: 36, height: 26, borderRadius: 6, fontSize: 18, display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', border: lang === l ? `2px solid ${C.violet}` : '2px solid transparent', background: lang === l ? `${C.violet}1A` : 'rgba(255,255,255,0.05)' }}>{flags[l]}</button>)}
      </div>

      <section style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', textAlign: 'center', padding: '60px 24px', position: 'relative', overflow: 'hidden' }}>
        <div style={{ position: 'absolute', top: -200, left: '50%', transform: 'translateX(-50%)', width: 900, height: 900, background: `radial-gradient(circle, ${C.violet}1F 0%, ${C.gold}0F 40%, transparent 70%)`, pointerEvents: 'none', animation: 'heroPulse 6s ease-in-out infinite' }} />
        <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 13, letterSpacing: 4, textTransform: 'uppercase', color: C.violet, marginBottom: 32 }}>{L(t.eye, lang)}</div>
        <h1 style={{ fontFamily: "'Playfair Display', serif", fontSize: 'clamp(38px, 6.5vw, 76px)', fontWeight: 900, lineHeight: 1.05, color: '#fff', maxWidth: 850, margin: 0 }}>
          {L(t.h1a, lang)}{' '}<span style={{ background: `linear-gradient(135deg, ${C.violet}, #C084FC)`, WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>{L(t.h1b, lang)}</span>{' '}{L(t.h1c, lang)}{' '}<span style={{ background: `linear-gradient(135deg, ${C.gold}, #FFD873)`, WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>{L(t.h1d, lang)}</span>
        </h1>
        <p style={{ fontFamily: "'Playfair Display', serif", fontSize: 'clamp(18px, 2.5vw, 26px)', fontStyle: 'italic', color: C.dim, maxWidth: 620, marginTop: 28 }}>{L(t.sub, lang)}</p>
        <div style={{ marginTop: 48, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8 }}>
          <div style={{ width: 60, height: 2, background: `linear-gradient(90deg, ${C.violet}, ${C.gold})`, marginBottom: 16 }} />
          <div style={{ fontWeight: 700, fontSize: 16, color: '#fff', letterSpacing: 1 }}>JUAN SCHUBERT</div>
          <div style={{ fontSize: 14, color: C.dim }}>ONIOKO · 10+ Years in Psychology & Human Cognition</div>
        </div>
        <div style={{ position: 'absolute', bottom: 40, left: '50%', transform: 'translateX(-50%)', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8 }}>
          <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 11, letterSpacing: 3, textTransform: 'uppercase', color: C.dim }}>{L(t.scroll, lang)}</span>
          <div style={{ width: 20, height: 20, borderRight: `2px solid ${C.violet}`, borderBottom: `2px solid ${C.violet}`, transform: 'rotate(45deg)', animation: 'bounceDown 2s ease-in-out infinite' }} />
        </div>
      </section>

      <article style={{ maxWidth: 760, margin: '0 auto', padding: '0 24px 120px' }}>
        <SH num="01" title={L(t.s1t, lang)} highlight={L(t.s1h, lang)} color={C.violet} />
        <p style={p}>{L(t.s1p1, lang)}</p>
        <PQ text={L(t.s1pq, lang)} color={C.violet} />
        <p style={p}>{L(t.s1p2, lang)}</p>
        <p style={p}>{L(t.s1p3, lang)}</p>
        <p style={p}>{L(t.s1p4, lang)}</p>
        <ST text={L(t.s1st, lang)} color={C.violet} />
        <Sep />

        <SH num="02" title={L(t.s2t, lang)} highlight={L(t.s2h, lang)} color={C.gold} />
        <p style={p}>{L(t.s2p1, lang)}</p>
        <PQ text={L(t.s2pq, lang)} color={C.gold} />
        <p style={p}>{L(t.s2p2, lang)}</p>
        <Scenario headerColor={C.gold} headerText={L(t.childH, lang)} speaker={lang === 'en' ? 'Child' : lang === 'de' ? 'Kind' : 'Niño'} speakerColor={C.gold} dialogue={L(t.childD, lang)} body={L(t.childB, lang)} analysis={L(t.childA, lang)} />
        <Scenario headerColor={C.cyan} headerText={L(t.adultH, lang)} speaker={lang === 'en' ? 'Adult' : lang === 'de' ? 'Erwachsener' : 'Adulto'} speakerColor={C.cyan} dialogue={L(t.adultD, lang)} body={L(t.adultB, lang)} analysis={L(t.adultA, lang)} />
        <p style={p}>{L(t.s2p3, lang)}</p>
        <ST text={L(t.s2st, lang)} color={C.gold} />
        <Sep />

        <SH num="03" title={L(t.s3t, lang)} highlight={L(t.s3h, lang)} color={C.cyan} />
        <p style={p}>{L(t.s3p1, lang)}</p>
        <p style={p}>{L(t.s3p2, lang)}</p>
        <p style={p}>{L(t.s3p3, lang)}</p>
        <p style={p}>{L(t.s3p4, lang)}</p>
        <PQ text={L(t.s3pq, lang)} color={C.cyan} />
        <p style={p}>{L(t.s3p5, lang)}</p>
        <p style={p}><em>{L(t.s3p6, lang)}</em></p>
        <Insight icon="🧠" title={L(t.s3insT, lang)} text={L(t.s3ins, lang)} color={C.rose} />
        <Sep />

        <SH num="04" title={L(t.s4t, lang)} highlight={L(t.s4h, lang)} color={C.green} />
        <p style={p}>{L(t.s4p1, lang)}</p>
        <p style={p}>{L(t.s4p2, lang)}</p>
        <p style={p}>{L(t.s4p3, lang)}</p>
        <Versus leftLabel={L(t.vsLL, lang)} leftTitle={L(t.vsLT, lang)} leftText={L(t.vsLB, lang)} rightLabel={L(t.vsRL, lang)} rightTitle={L(t.vsRT, lang)} rightText={L(t.vsRB, lang)} />
        <p style={p}>{L(t.s4p4, lang)}</p>
        <ST text={L(t.s4st, lang)} color={C.green} />
        <Sep />

        <SH num="05" title={L(t.s5t, lang)} highlight={L(t.s5h, lang)} color={C.rose} />
        <p style={p}>{L(t.s5p1, lang)}</p>
        <p style={p}>{L(t.s5p2, lang)}</p>
        <p style={p}>{L(t.s5p3, lang)}</p>
        <PQ text={L(t.s5pq, lang)} color={C.rose} />
        <p style={p}>{L(t.s5p4, lang)}</p>
        <p style={p}>{L(t.s5p5, lang)}</p>
        <Insight icon="🎭" title={L(t.s5insT, lang)} text={L(t.s5ins, lang)} color={C.amber} />
        <p style={p}>{L(t.s5p6, lang)}</p>
        <Sep />

        <SH num="06" title={L(t.s6t, lang)} highlight={L(t.s6h, lang)} color={C.amber} />
        <p style={p}>{L(t.s6p1, lang)}</p>
        <p style={p}>{L(t.s6p2, lang)}</p>
        <p style={p}>{L(t.s6p3, lang)}</p>
        <p style={p}>{L(t.s6p4, lang)}</p>
        <PQ text={L(t.s6pq, lang)} color={C.amber} />
        <p style={p}>{L(t.s6p5, lang)}</p>
        <p style={p}>{L(t.s6p6, lang)}</p>
        <ST text={L(t.s6st, lang)} color={C.amber} />
        <Sep />

        <SH num="07" title={L(t.s7t, lang)} highlight={L(t.s7h, lang)} color={C.violet} />
        <p style={p}>{L(t.s7p1, lang)}</p>
        <p style={p}>{L(t.s7p2, lang)}</p>
        <PQ text={L(t.s7pq, lang)} color={C.violet} />
        <p style={p}>{L(t.s7p3, lang)}</p>
        <p style={p}>{L(t.s7p4, lang)}</p>
        <p style={p}>{L(t.s7p5, lang)}</p>

        <div style={{ margin: '100px 0 80px', padding: '60px 40px', textAlign: 'center', position: 'relative', borderRadius: 20, background: `linear-gradient(135deg, ${C.violet}0F, ${C.gold}0A, ${C.rose}0F)`, border: `1px solid ${C.violet}26`, overflow: 'hidden' }}>
          <div style={{ position: 'absolute', inset: 0, background: `radial-gradient(ellipse at center, ${C.violet}1F, transparent 70%)`, pointerEvents: 'none', animation: 'finalePulse 4s ease-in-out infinite' }} />
          <p style={{ fontFamily: "'Playfair Display', serif", fontSize: 'clamp(26px, 4.5vw, 42px)', fontWeight: 900, fontStyle: 'italic', lineHeight: 1.3, color: '#fff', position: 'relative', zIndex: 1, margin: 0 }}>
            {L(t.finA, lang)}{' '}<span style={{ background: `linear-gradient(135deg, ${C.violet}, ${C.rose})`, WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>{L(t.finB, lang)}</span>
          </p>
        </div>

        <div style={{ marginTop: 80, paddingTop: 40, borderTop: '1px solid rgba(255,255,255,0.08)' }}>
          <p style={{ fontSize: 16, color: C.dim, lineHeight: 1.7, fontStyle: 'italic' }}><strong style={{ color: '#fff' }}>Juan Schubert</strong> · {L(t.bio, lang)}</p>
          <div style={{ marginTop: 24, display: 'flex', gap: 12, flexWrap: 'wrap' }}>
            {['#TheMoreYouLearn', '#CognitiveLiberty', '#HumanPlusMachine', '#ThinkLikeAChild'].map(tag => (
              <span key={tag} style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 12, padding: '6px 14px', borderRadius: 20, background: `${C.violet}1A`, color: C.violet, border: `1px solid ${C.violet}33` }}>{tag}</span>
            ))}
          </div>
        </div>
      </article>
    </div>
  );
}
